const fs = require('fs');
const path = require('path');

console.log('Generating 1000+ common Hindi words for App 29...');

// Existing audio files in assets/audio/hi/
const existingAudioDir = path.join(__dirname, 'master_audio_cache', 'hi');
const existingAudios = new Set(
  fs.existsSync(existingAudioDir)
    ? fs.readdirSync(existingAudioDir).map(f => f.replace('.mp3', ''))
    : []
);

// Helper function to create word entry
function w(id, hindi, english, category, emoji) {
  const hasHi = existingAudios.has(id);
  const hasEn = existingAudios.has(id);
  const hindiAudio = hasHi ? `assets/audio/hi/${id}.mp3` : 'assets/audio/hi/feedback_great.mp3';
  const englishAudio = hasEn ? `assets/audio/en/${id}.mp3` : 'assets/audio/en/feedback_great.mp3';
  return { id, hindi, english, category, emoji, hindiAudio, englishAudio };
}

const words = [
  // ================= 1. FOOD & DRINKS (70) =================
  w('paani', 'पानी', 'Water', 'food', '💧'),
  w('doodh', 'दूध', 'Milk', 'food', '🥛'),
  w('khaana', 'खाना', 'Food', 'food', '🍲'),
  w('chaawal', 'चावल', 'Rice', 'food', '🍚'),
  w('roti', 'रोटी', 'Bread / Roti', 'food', '🫓'),
  w('daal', 'दाल', 'Lentils', 'food', '🥣'),
  w('chai', 'चाय', 'Tea', 'food', '☕'),
  w('coffee', 'कॉफ़ी', 'Coffee', 'food', '☕'),
  w('shehad', 'शहद', 'Honey', 'food', '🍯'),
  w('cheeni', 'चीनी', 'Sugar', 'food', '🍬'),
  w('namak', 'नमक', 'Salt', 'food', '🧂'),
  w('ghee', 'घी', 'Butter Oil (Ghee)', 'food', '🧈'),
  w('makhan', 'मक्खन', 'Butter', 'food', '🧈'),
  w('dahi', 'दही', 'Curd / Yogurt', 'food', '🥣'),
  w('tel', 'तेल', 'Oil', 'food', '🛢️'),
  w('sharbat', 'शरबत', 'Syrup / Juice', 'food', '🧃'),
  w('lassi', 'लस्सी', 'Lassi', 'food', '🥛'),
  w('halwa', 'हलवा', 'Pudding (Halwa)', 'food', '🍮'),
  w('kheer', 'खीर', 'Rice Pudding', 'food', '🥣'),
  w('ladoo', 'लड्डू', 'Sweet Ball (Laddoo)', 'food', '🍘'),
  w('jalebi', 'जलेबी', 'Jalebi', 'food', '🍥'),
  w('barfi', 'बर्फी', 'Barfi', 'food', '🍬'),
  w('samosa', 'समोसा', 'Samosa', 'food', '🥟'),
  w('kachori', 'कचौरी', 'Kachori', 'food', '🥟'),
  w('pakoda', 'पकोड़ा', 'Fritter (Pakora)', 'food', '🧆'),
  w('paratha', 'पराठा', 'Flatbread (Paratha)', 'food', '🫓'),
  w('puri', 'पूरी', 'Puri', 'food', '🫓'),
  w('sabzi', 'सब्ज़ी', 'Vegetable Dish', 'food', '🥗'),
  w('raita', 'रायता', 'Raita', 'food', '🥣'),
  w('salad', 'सलाद', 'Salad', 'food', '🥗'),
  w('soup', 'सूप', 'Soup', 'food', '🍲'),
  w('biscuit', 'बिस्कुट', 'Biscuit', 'food', '🍪'),
  w('cake', 'केक', 'Cake', 'food', '🎂'),
  w('icecream', 'आइसक्रीम', 'Ice Cream', 'food', '🍦'),
  w('chocolate', 'चॉकलेट', 'Chocolate', 'food', '🍫'),
  w('mithai', 'मिठाई', 'Sweets', 'food', '🍬'),
  w('chutney', 'चटनी', 'Sauce (Chutney)', 'food', '🥣'),
  w('achar', 'अचार', 'Pickle', 'food', '🫙'),
  w('papad', 'पापड़', 'Crisp (Papad)', 'food', '🍘'),
  w('paneer', 'पनीर', 'Cottage Cheese', 'food', '🧀'),
  w('chana', 'चना', 'Chickpeas', 'food', '🧆'),
  w('rajma', 'राजमा', 'Kidney Beans', 'food', '🫘'),
  w('khichdi', 'खिचड़ी', 'Khichdi', 'food', '🍲'),
  w('poha', 'पोहा', 'Flattened Rice', 'food', '🥣'),
  w('idli', 'इडली', 'Rice Cake (Idli)', 'food', '⚪'),
  w('dosa', 'डोसा', 'Crepe (Dosa)', 'food', '🥞'),
  w('vada', 'वड़ा', 'Vada', 'food', '🍩'),
  w('upma', 'उपमा', 'Upma', 'food', '🥣'),
  w('haldi', 'हल्दी', 'Turmeric', 'food', '🟡'),
  w('mirch', 'मिर्च', 'Chilli', 'food', '🌶️'),
  w('dhaniya', 'धनिया', 'Coriander', 'food', '🌿'),
  w('jeera', 'जीरा', 'Cumin', 'food', '🌾'),
  w('adrak', 'अदरक', 'Ginger', 'food', '🫚'),
  w('lahsun', 'लहसुन', 'Garlic', 'food', '🧄'),
  w('ilaichi', 'इलायची', 'Cardamom', 'food', '🌱'),
  w('laung', 'लौंग', 'Clove', 'food', '🌱'),
  w('dalcheeni', 'दालचीनी', 'Cinnamon', 'food', '🪵'),
  w('saunf', 'सौंफ', 'Fennel Seed', 'food', '🌿'),
  w('kesar', 'केसर', 'Saffron', 'food', '🏵️'),
  w('hing', 'हींग', 'Asafoetida', 'food', '🧂'),
  w('badam', 'बादाम', 'Almond', 'food', '🥜'),
  w('kaju', 'काजू', 'Cashew', 'food', '🥜'),
  w('kismis', 'किशमिश', 'Raisin', 'food', '🍇'),
  w('akhrot', 'अखरोट', 'Walnut', 'food', '🌰'),
  w('pista', 'पिस्ता', 'Pistachio', 'food', '🥜'),
  w('mungphali', 'मूंगफली', 'Peanut', 'food', '🥜'),
  w('til', 'तिल', 'Sesame', 'food', '🌱'),
  w('gud', 'गुड़', 'Jaggery', 'food', '🟤'),
  w('rasgulla', 'रसगुल्ला', 'Rasgulla', 'food', '⚪'),
  w('gulabjamun', 'गुलाब जामुन', 'Gulab Jamun', 'food', '🟤'),

  // ================= 2. FRUITS & VEGETABLES (70) =================
  w('seb', 'सेब', 'Apple', 'fruits', '🍎'),
  w('aam', 'आम', 'Mango', 'fruits', '🥭'),
  w('kela', 'केला', 'Banana', 'fruits', '🍌'),
  w('angoor', 'अंगूर', 'Grapes', 'fruits', '🍇'),
  w('santara', 'संतरा', 'Orange', 'fruits', '🍊'),
  w('anaar', 'अनार', 'Pomegranate', 'fruits', '🍎'),
  w('ananas', 'अनानास', 'Pineapple', 'fruits', '🍍'),
  w('papeeta', 'पपीता', 'Papaya', 'fruits', '🍈'),
  w('tarbooj', 'तरबूज', 'Watermelon', 'fruits', '🍉'),
  w('kharbooja', 'खरबूजा', 'Melon', 'fruits', '🍈'),
  w('amrood', 'अमरूद', 'Guava', 'fruits', '🍐'),
  w('nashpati', 'नाशपाती', 'Pear', 'fruits', '🍐'),
  w('neebu', 'नींबू', 'Lemon', 'fruits', '🍋'),
  w('mosambi', 'मौसमी', 'Sweet Lime', 'fruits', '🍈'),
  w('chiku', 'चीकू', 'Sapodilla', 'fruits', '🥔'),
  w('jamun', 'जामुन', 'Blackberry', 'fruits', '🫐'),
  w('lechi', 'लीची', 'Lychee', 'fruits', '🍒'),
  w('cherry', 'चेरी', 'Cherry', 'fruits', '🍒'),
  w('strawberry', 'स्ट्रॉबेरी', 'Strawberry', 'fruits', '🍓'),
  w('ber', 'बेर', 'Jujube / Plum', 'fruits', '🫐'),
  w('aloo', 'आलू', 'Potato', 'fruits', '🥔'),
  w('tamatar', 'टमाटर', 'Tomato', 'fruits', '🍅'),
  w('pyaaz', 'प्याज़', 'Onion', 'fruits', '🧅'),
  w('matar', 'मटर', 'Peas', 'fruits', '🫛'),
  w('gajar', 'गाजर', 'Carrot', 'fruits', '🥕'),
  w('mooli', 'मूली', 'Radish', 'fruits', '🫚'),
  w('palak', 'पालक', 'Spinach', 'fruits', '🥬'),
  w('gobhi', 'गोभी', 'Cauliflower', 'fruits', '🥦'),
  w('bandgobhi', 'पत्ता गोभी', 'Cabbage', 'fruits', '🥬'),
  w('shimla_mirch', 'शिमला मिर्च', 'Capsicum', 'fruits', '🫑'),
  w('baingan', 'बैंगन', 'Brinjal / Eggplant', 'fruits', '🍆'),
  w('bhindi', 'भिंडी', 'Ladyfinger', 'fruits', '🌱'),
  w('lauki', 'लौकी', 'Bottle Gourd', 'fruits', '🥒'),
  w('karela', 'करेला', 'Bitter Gourd', 'fruits', '🥒'),
  w('kheera', 'खीरा', 'Cucumber', 'fruits', '🥒'),
  w('kaddu', 'कद्दू', 'Pumpkin', 'fruits', '🎃'),
  w('tinda', 'टिंडा', 'Apple Gourd', 'fruits', '🍈'),
  w('parwal', 'परवल', 'Pointed Gourd', 'fruits', '🥒'),
  w('shalgam', 'शलजम', 'Turnip', 'fruits', '🍠'),
  w('chukandar', 'चुकंदर', 'Beetroot', 'fruits', '🍠'),
  w('arbi', 'अरबी', 'Taro Root', 'fruits', '🥔'),
  w('sarson', 'सरसों', 'Mustard Greens', 'fruits', '🥬'),
  w('methi', 'मेथी', 'Fenugreek', 'fruits', '🌿'),
  w('pudina', 'पुदीना', 'Mint', 'fruits', '🌿'),
  w('kadi_patta', 'कढ़ी पत्ता', 'Curry Leaves', 'fruits', '🍃'),
  w('anjeer', 'अंजीर', 'Fig', 'fruits', '🫐'),
  w('aawla', 'आँवला', 'Gooseberry', 'fruits', '🟢'),
  w('sitaphal', 'सीताफल', 'Custard Apple', 'fruits', '🍈'),
  w('khajoor', 'खजूर', 'Dates', 'fruits', '🌴'),
  w('nariyal', 'नारियल', 'Coconut', 'fruits', '🥥'),
  w('shahatoot', 'शहतूत', 'Mulberry', 'fruits', '🫐'),
  w('kamrakh', 'कमरख', 'Starfruit', 'fruits', '⭐'),
  w('kathaal', 'कटहल', 'Jackfruit', 'fruits', '🍈'),
  w('singhada', 'सिंघाड़ा', 'Water Chestnut', 'fruits', '🌰'),
  w('drumstick', 'सहजन', 'Drumstick', 'fruits', '🎋'),
  w('mashroom', 'मशरूम', 'Mushroom', 'fruits', '🍄'),
  w('sweet_potato', 'शकरकंद', 'Sweet Potato', 'fruits', '🍠'),
  w('beans', 'फलियाँ', 'Green Beans', 'fruits', '🫛'),
  w('tori', 'तोरी', 'Ridge Gourd', 'fruits', '🥒'),
  w('bambookopal', 'बांस की कोपल', 'Bamboo Shoot', 'fruits', '🎋'),
  w('corn', 'मक्का', 'Corn / Maize', 'fruits', '🌽'),
  w('avocado', 'एवोकाडो', 'Avocado', 'fruits', '🥑'),
  w('kiwi', 'कीवी', 'Kiwi', 'fruits', '🥝'),
  w('blueberry', 'ब्लूबेरी', 'Blueberry', 'fruits', '🫐'),
  w('black_grape', 'काले अंगूर', 'Black Grapes', 'fruits', '🍇'),
  w('green_chilli', 'हरी मिर्च', 'Green Chilli', 'fruits', '🌶️'),
  w('red_chilli', 'लाल मिर्च', 'Red Chilli', 'fruits', '🌶️'),
  w('raw_mango', 'कच्चा आम', 'Raw Mango', 'fruits', '🥭'),
  w('dragon_fruit', 'ड्रैगन फ्रूट', 'Dragon Fruit', 'fruits', '🐉'),
  w('apricot', 'खुबानी', 'Apricot', 'fruits', '🍑'),

  // ================= 3. ANIMALS, BIRDS & CREATURES (80) =================
  w('kutta', 'कुत्ता', 'Dog', 'animals', '🐶'),
  w('billi', 'बिल्ली', 'Cat', 'animals', '🐱'),
  w('haathi', 'हाथी', 'Elephant', 'animals', '🐘'),
  w('sher', 'शेर', 'Lion', 'animals', '🦁'),
  w('cheetah', 'चीता', 'Cheetah', 'animals', '🐆'),
  w('bagh', 'बाघ', 'Tiger', 'animals', '🐅'),
  w('bhaloo', 'भालू', 'Bear', 'animals', '🐻'),
  w('bandar', 'बंदर', 'Monkey', 'animals', '🐵'),
  w('ghoda', 'घोड़ा', 'Horse', 'animals', '🐴'),
  w('gadha', 'गधा', 'Donkey', 'animals', '🫏'),
  w('khachhar', 'खच्चर', 'Mule', 'animals', '🫏'),
  w('gaay', 'गाय', 'Cow', 'animals', '🐮'),
  w('bail', 'बैल', 'Ox / Bull', 'animals', '🐂'),
  w('bhains', 'भैंस', 'Buffalo', 'animals', '🐃'),
  w('bakri', 'बकरी', 'Goat', 'animals', '🐐'),
  w('bhed', 'भेड़', 'Sheep', 'animals', '🐑'),
  w('oont', 'ऊँट', 'Camel', 'animals', '🐪'),
  w('hiran', 'हिरण', 'Deer', 'animals', '🦌'),
  w('khargosh', 'खरगोश', 'Rabbit', 'animals', '🐰'),
  w('chuha', 'चूहा', 'Mouse / Rat', 'animals', '🐭'),
  w('gilhari', 'गिलहरी', 'Squirrel', 'animals', '🐿️'),
  w('loomdi', 'लोमड़ी', 'Fox', 'animals', '🦊'),
  w('bhediya', 'भेड़िया', 'Wolf', 'animals', '🐺'),
  w('suar', 'सूअर', 'Pig', 'animals', '🐷'),
  w('zibra', 'ज़ेब्रा', 'Zebra', 'animals', '🦓'),
  w('giraff', 'जिराफ़', 'Giraffe', 'animals', '🦒'),
  w('genda', 'गैंडा', 'Rhinoceros', 'animals', '🦏'),
  w('daryai_ghoda', 'दरियाई घोड़ा', 'Hippopotamus', 'animals', '🦛'),
  w('kangaru', 'कंगारू', 'Kangaroo', 'animals', '🦘'),
  w('langur', 'लंगूर', 'Ape / Baboon', 'animals', '🦍'),
  w('chimpanzi', 'चिम्पांज़ी', 'Chimpanzee', 'animals', '🦧'),
  w('tota', 'तोता', 'Parrot', 'animals', '🦜'),
  w('mor', 'मोर', 'Peacock', 'animals', '🦚'),
  w('kabootar', 'कबूतर', 'Pigeon', 'animals', '🐦'),
  w('chidiya', 'चिड़िया', 'Sparrow', 'animals', '🐦'),
  w('kauwa', 'कौआ', 'Crow', 'animals', '🐦‍⬛'),
  w('hans', 'हंस', 'Swan', 'animals', '🦢'),
  w('battakh', 'बत्तख', 'Duck', 'animals', '🦆'),
  w('murgi', 'मुर्गी', 'Hen', 'animals', '🐔'),
  w('murga', 'मुर्गा', 'Rooster', 'animals', '🐓'),
  w('cheel', 'चील', 'Eagle', 'animals', '🦅'),
  w('baaz', 'बाज़', 'Falcon / Hawk', 'animals', '🦅'),
  w('ullu', 'उल्लू', 'Owl', 'animals', '🦉'),
  w('koel', 'कोयल', 'Cuckoo', 'animals', '🐦'),
  w('bagula', 'बगुला', 'Heron / Crane', 'animals', '🦤'),
  w('shaturmurg', 'शुतुरमुर्ग', 'Ostrich', 'animals', '🦤'),
  w('pinguin', 'पेंगुइन', 'Penguin', 'animals', '🐧'),
  w('chamgadar', 'चमगादड़', 'Bat', 'animals', '🦇'),
  w('titli', 'तितली', 'Butterfly', 'animals', '🦋'),
  w('madhumakhi', 'मधुमक्खी', 'Honeybee', 'animals', '🐝'),
  w('makhi', 'मक्खी', 'Housefly', 'animals', '🪰'),
  w('machhar', 'मच्छर', 'Mosquito', 'animals', '🦟'),
  w('cheenti', 'चींटी', 'Ant', 'animals', '🐜'),
  w('makdi', 'मकड़ी', 'Spider', 'animals', '🕷️'),
  w('bichhu', 'बिच्छू', 'Scorpion', 'animals', '🦂'),
  w('tiddi', 'टिड्डी', 'Grasshopper', 'animals', '🦗'),
  w('jugnoo', 'जुगनू', 'Firefly', 'animals', '🪲'),
  w('kechua', 'केंचुआ', 'Earthworm', 'animals', '🪱'),
  w('saanp', 'साँप', 'Snake', 'animals', '🐍'),
  w('chipkali', 'छिपकली', 'Lizard', 'animals', '🦎'),
  w('girgit', 'गिरगिट', 'Chameleon', 'animals', '🦎'),
  w('kachhua', 'कछुआ', 'Tortoise / Turtle', 'animals', '🐢'),
  w('mendhak', 'मेंढक', 'Frog', 'animals', '🐸'),
  w('magar', 'मगर', 'Crocodile', 'animals', '🐊'),
  w('ghariyal', 'घड़ियाल', 'Alligator', 'animals', '🐊'),
  w('machhli', 'मछली', 'Fish', 'animals', '🐟'),
  w('shark', 'शार्क', 'Shark', 'animals', '🦈'),
  w('whale', 'व्हेल', 'Whale', 'animals', '🐋'),
  w('dolphin', 'डॉल्फ़िन', 'Dolphin', 'animals', '🐬'),
  w('octopus', 'ऑक्टोपस', 'Octopus', 'animals', '🐙'),
  w('kekda', 'केकड़ा', 'Crab', 'animals', '🦀'),
  w('jheenga', 'झींगा', 'Prawn / Shrimp', 'animals', '🦐'),
  w('starfish', 'तारा मछली', 'Starfish', 'animals', '⭐'),
  w('seahorse', 'समुद्री घोड़ा', 'Seahorse', 'animals', '🐴'),
  w('jellyfish', 'जेलीफ़िश', 'Jellyfish', 'animals', '🪼'),
  w('yalk', 'याक', 'Yak', 'animals', '🐂'),
  w('nevala', 'नेवला', 'Mongoose', 'animals', '🦡'),
  w('sahi', 'साही', 'Porcupine', 'animals', '🦔'),
  w('lakadbaggha', 'लकड़बग्घा', 'Hyena', 'animals', '🐺'),
  w('panda', 'पांडा', 'Panda', 'animals', '🐼'),

  // ================= 4. BODY PARTS & HEALTH (60) =================
  w('aankh', 'आँख', 'Eye', 'body', '👁️'),
  w('naak', 'नाक', 'Nose', 'body', '👃'),
  w('kaan', 'कान', 'Ear', 'body', '👂'),
  w('munh', 'मुँह', 'Mouth', 'body', '👄'),
  w('daant', 'दाँत', 'Teeth', 'body', '🦷'),
  w('jeebh', 'जीभ', 'Tongue', 'body', '👅'),
  w('hoth', 'होंठ', 'Lips', 'body', '💋'),
  w('gaal', 'गाल', 'Cheek', 'body', '😊'),
  w('thodi', 'ठोड़ी', 'Chin', 'body', '🧔'),
  w('maatha', 'माथा', 'Forehead', 'body', '💆'),
  w('sir', 'सिर', 'Head', 'body', '🧑'),
  w('baal', 'बाल', 'Hair', 'body', '💇'),
  w('gardan', 'गर्दन', 'Neck', 'body', '🧣'),
  w('gala', 'गला', 'Throat', 'body', '🗣️'),
  w('kandha', 'कंधा', 'Shoulder', 'body', '💪'),
  w('seena', 'सीना', 'Chest', 'body', '🫁'),
  w('haath', 'हाथ', 'Hand', 'body', '✋'),
  w('bhuja', 'भुजा', 'Arm', 'body', '💪'),
  w('kohni', 'कोहनी', 'Elbow', 'body', '🦾'),
  w('kalai', 'कलाई', 'Wrist', 'body', '⌚'),
  w('hatheli', 'हथेली', 'Palm', 'body', '🤲'),
  w('ungli', 'उंगली', 'Finger', 'body', '☝️'),
  w('angutha', 'अंगूठा', 'Thumb', 'body', '👍'),
  w('nakhoon', 'नाखून', 'Nail', 'body', '💅'),
  w('pet', 'पेट', 'Stomach / Belly', 'body', '🤰'),
  w('kamar', 'कमर', 'Waist', 'body', '🧍'),
  w('peeth', 'पीठ', 'Back', 'body', '🚶'),
  w('jaangh', 'जाँघ', 'Thigh', 'body', '🦵'),
  w('ghutna', 'घुटना', 'Knee', 'body', '🦵'),
  w('taang', 'टाँग', 'Leg', 'body', '🦵'),
  w('pair', 'पैर', 'Foot', 'body', '🦶'),
  w('edhi', 'एड़ी', 'Heel', 'body', '👠'),
  w('panja', 'पंजा', 'Paw / Foot claw', 'body', '🐾'),
  w('dil', 'दिल', 'Heart', 'body', '❤️'),
  w('dimaag', 'दिमाग', 'Brain', 'body', '🧠'),
  w('haddi', 'हड्डी', 'Bone', 'body', '🦴'),
  w('khoon', 'खून', 'Blood', 'body', '🩸'),
  w('twacha', 'त्वचा', 'Skin', 'body', '🧴'),
  w('aansoo', 'आँसू', 'Tears', 'body', '😢'),
  w('paseena', 'पसीना', 'Sweat', 'body', '💦'),
  w('saans', 'साँस', 'Breath', 'body', '🌬️'),
  w('awaaz', 'आवाज़', 'Voice', 'body', '🎙️'),
  w('dhadkan', 'धड़कन', 'Heartbeat', 'body', '💓'),
  w('nayan', 'नयन', 'Eyes', 'body', '👀'),
  w('karna', 'कर्ण', 'Ear (Sanskrit)', 'body', '👂'),
  w('mukh', 'मुख', 'Face', 'body', '😀'),
  w('pad', 'पद', 'Foot (Formal)', 'body', '👣'),
  w('kar', 'कर', 'Hand (Formal)', 'body', '✋'),
  w('bhohe', 'भौंहें', 'Eyebrows', 'body', '🤨'),
  w('palak', 'पलक', 'Eyelash / Eyelid', 'body', '👁️'),
  w('dadhi', 'दाढ़ी', 'Beard', 'body', '🧔'),
  w('moochh', 'मूँछ', 'Mustache', 'body', '🥸'),
  w('swasthya', 'स्वास्थ्य', 'Health', 'body', '🩺'),
  w('dawa', 'दवा', 'Medicine', 'body', '💊'),
  w('bimari', 'बीमारी', 'Illness', 'body', '🤒'),
  w('bukhar', 'बुखार', 'Fever', 'body', '🌡️'),
  w('dard', 'दर्द', 'Pain', 'body', '🤕'),
  w('chot', 'चोट', 'Injury', 'body', '🩹'),
  w('marham', 'मरहम', 'Ointment', 'body', '🧴'),
  w('aaram', 'आराम', 'Rest / Relief', 'body', '🛌'),

  // ================= 5. NATURE, WEATHER & UNIVERSE (70) =================
  w('suraj', 'सूरज', 'Sun', 'nature', '☀️'),
  w('chand', 'चाँद', 'Moon', 'nature', '🌙'),
  w('taare', 'तारे', 'Stars', 'nature', '⭐'),
  w('aakash', 'आकाश', 'Sky', 'nature', '🌌'),
  w('gagan', 'गगन', 'Firmament / Sky', 'nature', '🌌'),
  w('baadal', 'बादल', 'Cloud', 'nature', '☁️'),
  w('baarish', 'बारिश', 'Rain', 'nature', '🌧️'),
  w('hawa', 'हवा', 'Air', 'nature', '💨'),
  w('pawan', 'पवन', 'Breeze / Wind', 'nature', '🍃'),
  w('toofan', 'तूफ़ान', 'Storm', 'nature', '🌪️'),
  w('bijli', 'बिजली', 'Lightning', 'nature', '⚡'),
  w('dhoop', 'धूप', 'Sunshine', 'nature', '🌞'),
  w('chhaon', 'छाँव', 'Shade / Shadow', 'nature', '⛱️'),
  w('kohra', 'कोहरा', 'Fog / Mist', 'nature', '🌫️'),
  w('barf', 'बर्फ़', 'Snow / Ice', 'nature', '❄️'),
  w('indradhanush', 'इंद्रधनुष', 'Rainbow', 'nature', '🌈'),
  w('dharti', 'धरती', 'Earth', 'nature', '🌍'),
  w('prithvi', 'पृथ्वी', 'Planet Earth', 'nature', '🌎'),
  w('mitti', 'मिट्टी', 'Soil / Mud', 'nature', '🪴'),
  w('ret', 'रेत', 'Sand', 'nature', '🏖️'),
  w('patthar', 'पत्थर', 'Stone / Rock', 'nature', '🪨'),
  w('pahad', 'पहाड़', 'Mountain', 'nature', '⛰️'),
  w('choti', 'चोटी', 'Peak / Summit', 'nature', '🏔️'),
  w('ghati', 'घाटी', 'Valley', 'nature', '🏞️'),
  w('nadi', 'नदी', 'River', 'nature', '🏞️'),
  w('samundar', 'समुंदर', 'Sea / Ocean', 'nature', '🌊'),
  w('sagar', 'सागर', 'Ocean', 'nature', '🌊'),
  w('lahar', 'लहर', 'Wave', 'nature', '🌊'),
  w('jheel', 'झील', 'Lake', 'nature', '🏞️'),
  w('jharna', 'झरना', 'Waterfall', 'nature', '💧'),
  w('talab', 'तालाब', 'Pond', 'nature', '🪷'),
  w('kinara', 'किनारा', 'Shore / Bank', 'nature', '🏖️'),
  w('dweep', 'द्वीप', 'Island', 'nature', '🏝️'),
  w('jungle', 'जंगल', 'Jungle', 'nature', '🌴'),
  w('van', 'वन', 'Forest', 'nature', '🌲'),
  w('ped', 'पेड़', 'Tree', 'nature', '🌳'),
  w('paudha', 'पौधा', 'Plant', 'nature', '🌱'),
  w('patta', 'पत्ता', 'Leaf', 'nature', '🍃'),
  w('daali', 'डाली', 'Branch', 'nature', '🌿'),
  w('tana', 'तना', 'Trunk', 'nature', '🪵'),
  w('jad', 'जड़', 'Root', 'nature', '🪴'),
  w('phool', 'फूल', 'Flower', 'nature', '🌸'),
  w('kamal', 'कमल', 'Lotus', 'nature', '🪷'),
  w('gulab', 'गुलाब', 'Rose', 'nature', '🌹'),
  w('chameli', 'चमेली', 'Jasmine', 'nature', '🌼'),
  w('surajmukhi', 'सूरजमुखी', 'Sunflower', 'nature', '🌻'),
  w('genda_phool', 'गेंदा', 'Marigold', 'nature', '🏵️'),
  w('kali', 'कली', 'Bud', 'nature', '🌷'),
  w('kaanta', 'काँटा', 'Thorn', 'nature', '🌵'),
  w('ghaas', 'घास', 'Grass', 'nature', '🌱'),
  w('aag', 'आग', 'Fire', 'nature', '🔥'),
  w('dhuaan', 'धुआँ', 'Smoke', 'nature', '💨'),
  w('raakh', 'राख', 'Ash', 'nature', '🌫️'),
  w('angara', 'अंगारा', 'Ember', 'nature', '🔥'),
  w('jal', 'जल', 'Water (Pure)', 'nature', '💧'),
  w('jyoti', 'ज्योति', 'Flame / Light', 'nature', '🕯️'),
  w('prakash', 'प्रकाश', 'Light', 'nature', '💡'),
  w('andhera', 'अंधेरा', 'Darkness', 'nature', '🌑'),
  w('ujala', 'उजाला', 'Daylight', 'nature', '☀️'),
  w('subah', 'सुबह', 'Morning', 'nature', '🌅'),
  w('dopahar', 'दोपहर', 'Afternoon', 'nature', '☀️'),
  w('shaam', 'शाम', 'Evening', 'nature', '🌇'),
  w('raat', 'रात', 'Night', 'nature', '🌃'),
  w('din', 'दिन', 'Day', 'nature', '📅'),
  w('suraj_ugna', 'सूर्योदय', 'Sunrise', 'nature', '🌅'),
  w('suraj_dubna', 'सूर्यास्त', 'Sunset', 'nature', '🌇'),
  w('graha', 'ग्रह', 'Planet', 'nature', '🪐'),
  w('mangal', 'मंगल', 'Mars', 'nature', '🔴'),
  w('brihaspati', 'बृहस्पति', 'Jupiter', 'nature', '🪐'),
  w('shani', 'शनि', 'Saturn', 'nature', '🪐'),

  // ================= 6. FAMILY & PEOPLE (50) =================
  w('papa', 'पापा', 'Father', 'family', '👨'),
  w('pita', 'पिता', 'Father (Formal)', 'family', '👨'),
  w('maa', 'माँ', 'Mother', 'family', '👩'),
  w('mata', 'माता', 'Mother (Formal)', 'family', '👩'),
  w('bhai', 'भाई', 'Brother', 'family', '👦'),
  w('behen', 'बहन', 'Sister', 'family', '👧'),
  w('dada', 'दादा', 'Paternal Grandfather', 'family', '👴'),
  w('dadi', 'दादी', 'Paternal Grandmother', 'family', '👵'),
  w('nana', 'नाना', 'Maternal Grandfather', 'family', '👴'),
  w('nani', 'नानी', 'Maternal Grandmother', 'family', '👵'),
  w('chacha', 'चाचा', 'Paternal Uncle', 'family', '👨'),
  w('chachi', 'चाची', 'Paternal Aunt', 'family', '👩'),
  w('mama', 'मामा', 'Maternal Uncle', 'family', '👨'),
  w('mami', 'मामी', 'Maternal Aunt', 'family', '👩'),
  w('bua', 'बुआ', 'Father\'s Sister', 'family', '👩'),
  w('fufa', 'फूफा', 'Uncle (Bua\'s husband)', 'family', '👨'),
  w('mausi', 'मौसी', 'Mother\'s Sister', 'family', '👩'),
  w('mausa', 'मौसा', 'Maternal Uncle', 'family', '👨'),
  w('beta', 'बेटा', 'Son', 'family', '👦'),
  w('beti', 'बेटी', 'Daughter', 'family', '👧'),
  w('pota', 'पोता', 'Grandson', 'family', '👦'),
  w('poti', 'पोती', 'Granddaughter', 'family', '👧'),
  w('bachha', 'बच्चा', 'Child', 'family', '🧒'),
  w('shishu', 'शिशु', 'Infant / Baby', 'family', '👶'),
  w('ladka', 'लड़का', 'Boy', 'family', '👦'),
  w('ladki', 'लड़की', 'Girl', 'family', '👧'),
  w('purush', 'पुरुष', 'Man', 'family', '👨'),
  w('mahila', 'महिला', 'Woman', 'family', '👩'),
  w('aadmi', 'आदमी', 'Person / Man', 'family', '👨'),
  w('aurat', 'औरत', 'Woman', 'family', '👩'),
  w('dost', 'दोस्त', 'Friend', 'family', '🤝'),
  w('mitra', 'मित्र', 'Friend (Formal)', 'family', '🧑‍🤝‍🧑'),
  w('saheli', 'सहेली', 'Female Friend', 'family', '👭'),
  w('parivar', 'परिवार', 'Family', 'family', '👨‍👩‍👧‍👦'),
  w('rishtedaar', 'रिश्तेदार', 'Relative', 'family', '👥'),
  w('mehmaan', 'मेहमान', 'Guest', 'family', '🙋'),
  w('padosi', 'पड़ोसी', 'Neighbor', 'family', '🏡'),
  w('guru', 'गुरु', 'Mentor / Master', 'family', '🧘'),
  w('shishya', 'शिष्य', 'Disciple / Pupil', 'family', '🙇'),
  w('shikshak', 'शिक्षक', 'Teacher', 'family', '👨‍🏫'),
  w('shikshika', 'शिक्षिका', 'Lady Teacher', 'family', '👩‍🏫'),
  w('vidyarthi', 'विद्यार्थी', 'Student', 'family', '🧑‍🎓'),
  w('doctor', 'डॉक्टर', 'Doctor', 'family', '👨‍⚕️'),
  w('nurse', 'नर्स', 'Nurse', 'family', '👩‍⚕️'),
  w('kisaan', 'किसान', 'Farmer', 'family', '👨‍🌾'),
  w('sipahi', 'सिपाही', 'Soldier / Constable', 'family', '👮'),
  w('police', 'पुलिस', 'Police', 'family', '👮'),
  w('daakiya', 'डाकिया', 'Postman', 'family', '📫'),
  w('driver', 'चालक', 'Driver', 'family', '🧑‍✈️'),
  w('dada_dadi', 'बुजुर्ग', 'Elderly', 'family', '🧓'),

  // ================= 7. HOME, ROOMS & FURNITURE (70) =================
  w('ghar', 'घर', 'Home / House', 'home', '🏠'),
  w('makaan', 'मकान', 'Building / House', 'home', '🏡'),
  w('kamra', 'कमरा', 'Room', 'home', '🚪'),
  w('darwaza', 'दरवाजा', 'Door', 'home', '🚪'),
  w('khidki', 'खिड़की', 'Window', 'home', '🪟'),
  w('chhat', 'छत', 'Roof / Ceiling', 'home', '🏠'),
  w('deewar', 'दीवार', 'Wall', 'home', '🧱'),
  w('farsh', 'फ़र्श', 'Floor', 'home', '🧹'),
  w('aangan', 'आँगन', 'Courtyard', 'home', '🏡'),
  w('balcony', 'बालकनी', 'Balcony', 'home', '🪴'),
  w('rasoi', 'रसोई', 'Kitchen', 'home', '🍳'),
  w('gusal_khana', 'स्नानघर', 'Bathroom', 'home', '🚿'),
  w('bithak', 'बैठक', 'Living Room', 'home', '🛋️'),
  w('sofa', 'सोफ़ा', 'Sofa', 'home', '🛋️'),
  w('mez', 'मेज़', 'Table', 'home', '🪑'),
  w('kursi', 'कुर्सी', 'Chair', 'home', '💺'),
  w('bistar', 'बिस्तर', 'Bed', 'home', '🛏️'),
  w('gadda', 'गद्दा', 'Mattress', 'home', '🛏️'),
  w('takiya', 'तकिया', 'Pillow', 'home', '🛌'),
  w('chadar', 'चादर', 'Bedsheet', 'home', '🛏️'),
  w('kambal', 'कंबल', 'Blanket', 'home', '🛋️'),
  w('rajai', 'रज़ाई', 'Quilt', 'home', '🛌'),
  w('almari', 'अलमारी', 'Cupboard / Wardrobe', 'home', '🗄️'),
  w('parda', 'पर्दा', 'Curtain', 'home', '🪟'),
  w('pankha', 'पंखा', 'Fan', 'home', '🪭'),
  w('cooler', 'कूलर', 'Cooler', 'home', '❄️'),
  w('ac', 'वातानुकूलक', 'Air Conditioner', 'home', '❄️'),
  w('bulb', 'बल्ब', 'Bulb / Lamp', 'home', '💡'),
  w('tube', 'ट्यूबलाइट', 'Tube Light', 'home', '💡'),
  w('taala', 'ताला', 'Lock', 'home', '🔒'),
  w('chaabi', 'चाबी', 'Key', 'home', '🔑'),
  w('ghadi', 'घड़ी', 'Clock / Watch', 'home', '⏰'),
  w('aaina', 'आईना', 'Mirror', 'home', '🪞'),
  w('darpan', 'दर्पण', 'Mirror (Formal)', 'home', '🪞'),
  w('comb', 'कंघी', 'Comb', 'home', '🪮'),
  w('sabun', 'साबुन', 'Soap', 'home', '🧼'),
  w('tauliya', 'तौलिया', 'Towel', 'home', '🧖'),
  w('balti', 'बाल्टी', 'Bucket', 'home', '🪣'),
  w('magga', 'मग्गा', 'Mug', 'home', '🥛'),
  w('nal', 'नल', 'Tap / Faucet', 'home', '🚰'),
  w('pipe', 'पाइप', 'Pipe', 'home', '🪠'),
  w('jhaadoo', 'झाड़ू', 'Broom', 'home', '🧹'),
  w('pocha', 'पोछा', 'Mop', 'home', '🧽'),
  w('kudedaan', 'कूड़ेदान', 'Dustbin', 'home', '🗑️'),
  w('chammach', 'चम्मच', 'Spoon', 'home', '🥄'),
  w('kaanta_chamach', 'काँटा', 'Fork', 'home', '🍴'),
  w('chaku', 'चाकू', 'Knife', 'home', '🔪'),
  w('thaali', 'थाली', 'Plate', 'home', '🍽️'),
  w('katori', 'कटोरी', 'Bowl', 'home', '🥣'),
  w('gilaas', 'गिलास', 'Tumbler / Glass', 'home', '🥛'),
  w('kap', 'कप', 'Cup', 'home', '☕'),
  w('saucer', 'तश्तरी', 'Saucer', 'home', '☕'),
  w('jag', 'जग', 'Jug', 'home', '🫖'),
  w('bottle', 'बोतल', 'Bottle', 'home', '🍼'),
  w('kadai', 'कड़ाही', 'Wok / Pan', 'home', '🍳'),
  w('tawa', 'तवा', 'Griddle (Tawa)', 'home', '🍳'),
  w('belan', 'बेलन', 'Rolling Pin', 'home', '🥖'),
  w('chakla', 'चकला', 'Rolling Board', 'home', '⚪'),
  w('chimta', 'चिमटा', 'Tongs', 'home', '🥢'),
  w('chulha', 'चूल्हा', 'Stove', 'home', '🔥'),
  w('gas', 'गैस स्टोव', 'Gas Stove', 'home', '🍳'),
  w('cylinder', 'गैस सिलेंडर', 'Cylinder', 'home', '🛢️'),
  w('fridge', 'फ़्रिज', 'Refrigerator', 'home', '🧊'),
  w('tv', 'टीवी', 'Television', 'home', '📺'),
  w('radio', 'रेडियो', 'Radio', 'home', '📻'),
  w('telephone', 'फ़ोन', 'Phone', 'home', '☎️'),
  w('matka', 'मटका', 'Clay Pitcher', 'home', '🏺'),
  w('surahi', 'सुराही', 'Ewer / Clay flask', 'home', '🏺'),
  w('dabba', 'डिब्बा', 'Box / Container', 'home', '📦'),
  w('bori', 'बोरी', 'Sack / Bag', 'home', '🛍️'),

  // ================= 8. CLOTHES & ACCESSORIES (60) =================
  w('kapda', 'कपड़ा', 'Cloth', 'clothes', '👗'),
  w('kurta', 'कुर्ता', 'Tunic / Kurta', 'clothes', '👕'),
  w('pajama', 'पाजामा', 'Pajamas', 'clothes', '👖'),
  w('shirt', 'कमीज़', 'Shirt', 'clothes', '👔'),
  w('pant', 'पतलून', 'Trousers', 'clothes', '👖'),
  w('sari', 'साड़ी', 'Saree', 'clothes', '🥻'),
  w('dhoti', 'धोती', 'Dhoti', 'clothes', '🥻'),
  w('frock', 'फ़्रॉक', 'Frock / Dress', 'clothes', '👗'),
  w('topi', 'टोपी', 'Cap / Hat', 'clothes', '🧢'),
  w('pagdi', 'पगड़ी', 'Turban', 'clothes', '👳'),
  w('dupatta', 'दुपट्टा', 'Scarf / Stole', 'clothes', '🧣'),
  w('rumal', 'रूमाल', 'Handkerchief', 'clothes', '🧻'),
  w('joota', 'जूता', 'Shoe', 'clothes', '👟'),
  w('chappal', 'चप्पल', 'Slippers / Sandals', 'clothes', '🩴'),
  w('moza', 'मोज़ा', 'Socks', 'clothes', '🧦'),
  w('sweater', 'स्वेटर', 'Sweater', 'clothes', '🧥'),
  w('jacket', 'जैकेट', 'Jacket', 'clothes', '🧥'),
  w('kot', 'कोट', 'Coat', 'clothes', '🧥'),
  w('shal', 'शॉल', 'Shawl', 'clothes', '🧣'),
  w('glove', 'दस्ताने', 'Gloves', 'clothes', '🧤'),
  w('chashma', 'चश्मा', 'Spectacles / Glasses', 'clothes', '👓'),
  w('dhup_chashma', 'धूप का चश्मा', 'Sunglasses', 'clothes', '🕶️'),
  w('batan', 'बटन', 'Button', 'clothes', '🔘'),
  w('dhaaga', 'धागा', 'Thread', 'clothes', '🧵'),
  w('sui', 'सुई', 'Needle', 'clothes', '🪡'),
  w('chain', 'ज़िप / चेन', 'Zipper', 'clothes', '🤐'),
  w('patti', 'पेटी / बेल्ट', 'Belt', 'clothes', '🥋'),
  w('chhatri', 'छतरी', 'Umbrella', 'clothes', '☂️'),
  w('raincoat', 'बरसाती', 'Raincoat', 'clothes', '🧥'),
  w('bangle', 'चूड़ी', 'Bangle', 'clothes', '💍'),
  w('anguthi', 'अंगूठी', 'Ring', 'clothes', '💍'),
  w('haar', 'हार', 'Necklace', 'clothes', '📿'),
  w('payal', 'पायल', 'Anklet', 'clothes', '✨'),
  w('kangan', 'कंगन', 'Bracelet', 'clothes', '🪙'),
  w('jhumka', 'झुमका', 'Earring', 'clothes', '💎'),
  w('bindi', 'बिंदी', 'Bindi', 'clothes', '🔴'),
  w('kajal', 'काजल', 'Kohl / Eyeliner', 'clothes', '👁️'),
  w('sindoor', 'सिंदूर', 'Vermilion', 'clothes', '🔴'),
  w('mehendi', 'मेहंदी', 'Henna', 'clothes', '🌿'),
  w('rang', 'रंग', 'Color', 'clothes', '🎨'),
  w('laal', 'लाल', 'Red', 'clothes', '🔴'),
  w('peela', 'पीला', 'Yellow', 'clothes', '🟡'),
  w('neela', 'नीला', 'Blue', 'clothes', '🔵'),
  w('hara', 'हरा', 'Green', 'clothes', '🟢'),
  w('safed', 'सफ़ेद', 'White', 'clothes', '⚪'),
  w('kaala', 'काला', 'Black', 'clothes', '⚫'),
  w('gulabi', 'गुलाबी', 'Pink', 'clothes', '🌸'),
  w('baingani', 'बैंगनी', 'Purple / Violet', 'clothes', '🟣'),
  w('bhoora', 'भूरा', 'Brown', 'clothes', '🟤'),
  w('kesariya', 'केसरिया', 'Orange / Saffron', 'clothes', '🟠'),
  w('sunehra', 'सुनहरा', 'Golden', 'clothes', '🪙'),
  w('chandi_rang', 'चांदी जैसा', 'Silver', 'clothes', '🥈'),
  w('resham', 'रेशम', 'Silk', 'clothes', '🧣'),
  w('soot', 'सूत / कपास', 'Cotton', 'clothes', '☁️'),
  w('oon', 'ऊन', 'Wool', 'clothes', '🧶'),
  w('chamda', 'चमड़ा', 'Leather', 'clothes', '👞'),
  w('khadi', 'खादी', 'Homespun Cloth', 'clothes', '🧵'),
  w('zari', 'ज़री', 'Brocade / Zari', 'clothes', '✨'),
  w('pocket', 'जेब', 'Pocket', 'clothes', '👝'),
  w('tailor', 'दर्ज़ी', 'Tailor', 'clothes', '🪡'),

  // ================= 9. VEHICLES & TRANSPORT (50) =================
  w('gaadi', 'गाड़ी', 'Car / Vehicle', 'vehicles', '🚗'),
  w('motor_car', 'मोटर कार', 'Motor Car', 'vehicles', '🚘'),
  w('bus', 'बस', 'Bus', 'vehicles', '🚌'),
  w('cycle', 'साइकिल', 'Bicycle', 'vehicles', '🚲'),
  w('motorcycle', 'मोटरसाइकिल', 'Motorcycle', 'vehicles', '🏍️'),
  w('scooter', 'स्कूटर', 'Scooter', 'vehicles', '🛵'),
  w('auto', 'ऑटो रिक्शा', 'Auto Rickshaw', 'vehicles', '🛺'),
  w('rickshaw', 'रिक्शा', 'Rickshaw', 'vehicles', '🛺'),
  w('tanga', 'तांगा', 'Horse Cart', 'vehicles', '🐎'),
  w('bailgaadi', 'बैलगाड़ी', 'Bullock Cart', 'vehicles', '🐂'),
  w('railgaadi', 'रेलगाड़ी', 'Train', 'vehicles', '🚂'),
  w('metro', 'मेट्रो ट्रेन', 'Metro Train', 'vehicles', '🚇'),
  w('maalgaadi', 'मालगाड़ी', 'Goods Train', 'vehicles', '🚆'),
  w('vimaan', 'विमान', 'Aeroplane', 'vehicles', '✈️'),
  w('hawai_jahaz', 'हवाई जहाज़', 'Airplane', 'vehicles', '🛫'),
  w('helicopter', 'हेलिकॉप्टर', 'Helicopter', 'vehicles', '🚁'),
  w('rocket', 'रॉकेट', 'Rocket', 'vehicles', '🚀'),
  w('naav', 'नाव', 'Boat', 'vehicles', '⛵'),
  w('kisti', 'किश्ती', 'Rowboat', 'vehicles', '🛶'),
  w('jahaz', 'पानी का जहाज़', 'Ship', 'vehicles', '🚢'),
  w('steamer', 'स्टीमर', 'Steamer Boat', 'vehicles', '⛴️'),
  w('submarin', 'पनडुब्बी', 'Submarine', 'vehicles', '🤿'),
  w('truck', 'ट्रक', 'Truck / Lorry', 'vehicles', '🚚'),
  w('tractor', 'ट्रैक्टर', 'Tractor', 'vehicles', '🚜'),
  w('ambulance', 'एम्बुलेंस', 'Ambulance', 'vehicles', '🚑'),
  w('fire_truck', 'दमकल गाड़ी', 'Fire Engine', 'vehicles', '🚒'),
  w('police_car', 'पुलिस गाड़ी', 'Police Patrol', 'vehicles', '🚓'),
  w('taxi', 'टैक्सी', 'Taxi / Cab', 'vehicles', '🚕'),
  w('van', 'वैन', 'Van', 'vehicles', '🚐'),
  w('jeep', 'जीप', 'Jeep', 'vehicles', '🚙'),
  w('thela', 'ठेला', 'Handcart', 'vehicles', '🛒'),
  w('sadak', 'सड़क', 'Road', 'vehicles', '🛣️'),
  w('raasta', 'रास्ता', 'Path / Way', 'vehicles', '🛤️'),
  w('gali', 'गली', 'Street / Lane', 'vehicles', '🏘️'),
  w('chauraha', 'चौराहा', 'Crossroads', 'vehicles', '🚦'),
  w('signal', 'बत्ती / सिग्नल', 'Traffic Light', 'vehicles', '🚥'),
  w('pul', 'पुल', 'Bridge', 'vehicles', '🌉'),
  w('surang', 'सुरंग', 'Tunnel', 'vehicles', '🚇'),
  w('patari', 'रेल की पटरी', 'Railway Track', 'vehicles', '🛤️'),
  w('station', 'रेलवे स्टेशन', 'Railway Station', 'vehicles', '🚉'),
  w('bus_adda', 'बस अड्डा', 'Bus Stand', 'vehicles', '🚏'),
  w('hawai_adda', 'हवाई अड्डा', 'Airport', 'vehicles', '🛬'),
  w('bandargah', 'बंदरगाह', 'Seaport / Harbor', 'vehicles', '⚓'),
  w('ticket', 'टिकट', 'Ticket', 'vehicles', '🎫'),
  w('seat', 'सीट', 'Seat', 'vehicles', '💺'),
  w('pahiya', 'पहिया', 'Wheel', 'vehicles', '🛞'),
  w('horn', 'हॉर्न', 'Horn', 'vehicles', '📢'),
  w('petrol', 'पेट्रोल', 'Petrol / Fuel', 'vehicles', '⛽'),
  w('diesel', 'डीज़ल', 'Diesel', 'vehicles', '⛽'),
  w('helment', 'हेलमेट', 'Helmet', 'vehicles', '⛑️'),

  // ================= 10. SCHOOL & STATIONERY (60) =================
  w('kitaab', 'किताब', 'Book', 'school', '📚'),
  w('pustak', 'पुस्तक', 'Book (Formal)', 'school', '📖'),
  w('copy', 'कॉपी', 'Notebook', 'school', '📓'),
  w('kalam', 'कलम', 'Pen', 'school', '🖊️'),
  w('pencil', 'पेंसिल', 'Pencil', 'school', '✏️'),
  w('rubber', 'रबर', 'Eraser', 'school', '🧼'),
  w('sharpner', 'कटर / शार्पनर', 'Sharpener', 'school', '🪒'),
  w('scale', 'पैमाना / फुटा', 'Ruler / Scale', 'school', '📏'),
  w('basta', 'बस्ता', 'School Bag', 'school', '🎒'),
  w('school', 'स्कूल', 'School', 'school', '🏫'),
  w('vidyalaya', 'विद्यालय', 'School (Hindi)', 'school', '🏫'),
  w('kaksha', 'कक्षा', 'Classroom', 'school', '👩‍🏫'),
  w('blackboard', 'श्यामपट्ट', 'Blackboard', 'school', '⬛'),
  w('chalk', 'खड़िया / चॉक', 'Chalk', 'school', '🖍️'),
  w('duster', 'डस्टर', 'Duster', 'school', '🧽'),
  w('bench', 'बेंच', 'Bench', 'school', '🪑'),
  w('ghanti', 'घंटी', 'Bell', 'school', '🔔'),
  w('prathana', 'प्रार्थना', 'Assembly Prayer', 'school', '🙏'),
  w('chhutti', 'छुट्टी', 'Holiday / Recess', 'school', '🏖️'),
  w('tiffin', 'टिफ़िन', 'Lunchbox', 'school', '🍱'),
  w('water_bottle', 'पानी की बोतल', 'Water Bottle', 'school', '🍶'),
  w('paper', 'काग़ज़', 'Paper', 'school', '📄'),
  w('drawing', 'चित्रकला', 'Drawing', 'school', '🎨'),
  w('rang_pencil', 'रंगीन पेंसिल', 'Color Pencils', 'school', '🖍️'),
  w('gond', 'गोंद', 'Glue', 'school', '🧴'),
  w('kainchi', 'कैंची', 'Scissors', 'school', '✂️'),
  w('pustakalaya', 'पुस्तकालय', 'Library', 'school', '📚'),
  w('khel_maidan', 'खेल का मैदान', 'Playground', 'school', '⚽'),
  w('patra', 'पत्र', 'Letter', 'school', '✉️'),
  w('khat', 'खत', 'Letter / Note', 'school', '✉️'),
  w('lekh', 'लेख', 'Essay / Article', 'school', '📝'),
  w('kavita', 'कविता', 'Poem', 'school', '📜'),
  w('kahani', 'कहानी', 'Story', 'school', '📖'),
  w('gana', 'गाना', 'Song', 'school', '🎵'),
  w('naach', 'नाच', 'Dance', 'school', '💃'),
  w('naatak', 'नाटक', 'Drama / Play', 'school', '🎭'),
  w('pariksha', 'परीक्षा', 'Exam / Test', 'school', '📋'),
  w('ank', 'अंक', 'Marks / Numbers', 'school', '💯'),
  w('prashna', 'प्रश्न', 'Question', 'school', '❓'),
  w('uttar', 'उत्तर', 'Answer', 'school', '✅'),
  w('paath', 'पाठ', 'Lesson', 'school', '📖'),
  w('shabda', 'शब्द', 'Word', 'school', '🔤'),
  w('varnamala', 'वर्णमाला', 'Alphabet', 'school', '🔤'),
  w('akshar', 'अक्षर', 'Letter / Character', 'school', '🅰️'),
  w('matra', 'मात्रा', 'Vowel Sign', 'school', '✍️'),
  w('vakya', 'वाक्य', 'Sentence', 'school', '📜'),
  w('bhasha', 'भाषा', 'Language', 'school', '🗣️'),
  w('hindi', 'हिन्दी', 'Hindi', 'school', '🇮🇳'),
  w('english', 'अंग्रेज़ी', 'English', 'school', '🇬🇧'),
  w('ganit', 'गणित', 'Mathematics', 'school', '➗'),
  w('vigyan', 'विज्ञान', 'Science', 'school', '🔬'),
  w('itihaas', 'इतिहास', 'History', 'school', '📜'),
  w('bhugol', 'भूगोल', 'Geography', 'school', '🌍'),
  w('naksha', 'नक्शा', 'Map', 'school', '🗺️'),
  w('globe', 'ग्लोब', 'Globe', 'school', '🌐'),
  w('computer', 'कंप्यूटर', 'Computer', 'school', '💻'),
  w('medal', 'पदक', 'Medal', 'school', '🏅'),
  w('trophy', 'ट्रॉफ़ी', 'Trophy', 'school', '🏆'),
  w('puraskar', 'पुरस्कार', 'Award / Prize', 'school', '🎁'),
  w('pramanpatra', 'प्रमाण पत्र', 'Certificate', 'school', '📜'),

  // ================= 11. ACTIONS & VERBS (100) =================
  w('aana', 'आना', 'To Come', 'actions', '🚶'),
  w('jaana', 'जाना', 'To Go', 'actions', '🏃'),
  w('khana', 'खाना', 'To Eat', 'actions', '🍽️'),
  w('peena', 'पीना', 'To Drink', 'actions', '🥤'),
  w('sona', 'सोना', 'To Sleep', 'actions', '😴'),
  w('jagana', 'जागना', 'To Wake Up', 'actions', '⏰'),
  w('padhna', 'पढ़ना', 'To Read / Study', 'actions', '📖'),
  w('likhna', 'लिखना', 'To Write', 'actions', '✍️'),
  w('bolna', 'बोलना', 'To Speak', 'actions', '🗣️'),
  w('kahna', 'कहना', 'To Tell / Say', 'actions', '💬'),
  w('sunna', 'सुनना', 'To Listen / Hear', 'actions', '👂'),
  w('dekhna', 'देखना', 'To Look / See', 'actions', '👀'),
  w('hasna', 'हँसना', 'To Laugh', 'actions', '😄'),
  w('rona', 'रोना', 'To Cry', 'actions', '😭'),
  w('gaana', 'गाना', 'To Sing', 'actions', '🎤'),
  w('nachna', 'नाचना', 'To Dance', 'actions', '💃'),
  w('khelna', 'खेलना', 'To Play', 'actions', '⚽'),
  w('koodna', 'कूदना', 'To Jump', 'actions', '🦘'),
  w('daudna', 'दौड़ना', 'To Run', 'actions', '🏃'),
  w('chalna', 'चलना', 'To Walk', 'actions', '🚶'),
  w('baithna', 'बैठना', 'To Sit', 'actions', '🪑'),
  w('khade_hona', 'खड़े होना', 'To Stand', 'actions', '🧍'),
  w('rukna', 'रुकना', 'To Stop', 'actions', '🛑'),
  w('chalana', 'चलाना', 'To Drive / Move', 'actions', '🚗'),
  w('udna', 'उड़ना', 'To Fly', 'actions', '🕊️'),
  w('tairna', 'तैरना', 'To Swim', 'actions', '🏊'),
  w('doobna', 'डूबना', 'To Sink / Drown', 'actions', '🤿'),
  w('nahana', 'नहाना', 'To Bathe', 'actions', '🚿'),
  w('dhona', 'धोना', 'To Wash', 'actions', '🧼'),
  w('saaf_karna', 'साफ़ करना', 'To Clean', 'actions', '🧹'),
  w('pakhana', 'पकाना', 'To Cook', 'actions', '🍳'),
  w('talna', 'तलना', 'To Fry', 'actions', '🍳'),
  w('ubalna', 'उबालना', 'To Boil', 'actions', '🫖'),
  w('kaatna', 'काटना', 'To Cut', 'actions', '✂️'),
  w('chhilna', 'छीलना', 'To Peel', 'actions', '🥔'),
  w('peetna', 'पीटना', 'To Beat', 'actions', '🥁'),
  w('maarna', 'मारना', 'To Hit', 'actions', '🥊'),
  w('bachana', 'बचाना', 'To Save', 'actions', '🛡️'),
  w('dena', 'देना', 'To Give', 'actions', '🤲'),
  w('lena', 'लेना', 'To Take', 'actions', '🤝'),
  w('paana', 'पाना', 'To Get / Find', 'actions', '🎁'),
  w('khona', 'खोना', 'To Lose', 'actions', '❓'),
  w('dhoondna', 'ढूँढना', 'To Search', 'actions', '🔍'),
  w('milna', 'मिलना', 'To Meet / Find', 'actions', '🤝'),
  w('puchhna', 'पूछना', 'To Ask', 'actions', '🙋'),
  w('bataana', 'बताना', 'To Inform', 'actions', '🗣️'),
  w('samajhna', 'समझना', 'To Understand', 'actions', '💡'),
  w('sochna', 'सोचना', 'To Think', 'actions', '🤔'),
  w('yaad_karna', 'याद करना', 'To Remember', 'actions', '💭'),
  w('bhoolna', 'भूलना', 'To Forget', 'actions', '🤷'),
  w('seekhna', 'सीखना', 'To Learn', 'actions', '📚'),
  w('sikhana', 'सिखाना', 'To Teach', 'actions', '👨‍🏫'),
  w('muskurana', 'मुस्कुराना', 'To Smile', 'actions', '😊'),
  w('chillaana', 'चिल्लाना', 'To Shout', 'actions', '📢'),
  w('phoonkna', 'फूँकना', 'To Blow', 'actions', '💨'),
  w('phenkna', 'फेंकना', 'To Throw', 'actions', '🥏'),
  w('pakadna', 'पकड़ना', 'To Catch / Hold', 'actions', '🧤'),
  w('kheenchana', 'खींचना', 'To Pull', 'actions', '🪢'),
  w('dhakelna', 'धकेलना', 'To Push', 'actions', '🛒'),
  w('girna', 'गिरना', 'To Fall', 'actions', '🍂'),
  w('uthaana', 'उठाना', 'To Lift / Pick up', 'actions', '🏋️'),
  w('chadhna', 'चढ़ना', 'To Climb', 'actions', '🧗'),
  w('utarna', 'उतरना', 'To Descend', 'actions', '🧗'),
  w('kholna', 'खोलना', 'To Open', 'actions', '🔓'),
  w('band_karna', 'बंद करना', 'To Close', 'actions', '🔒'),
  w('chhipna', 'छिपना', 'To Hide', 'actions', '🫣'),
  w('chhipana', 'छिपाना', 'To Conceal', 'actions', '🙈'),
  w('choona', 'छूना', 'To Touch', 'actions', '👉'),
  w('soonghna', 'सूँघना', 'To Smell', 'actions', '👃'),
  w('chakhna', 'चखना', 'To Taste', 'actions', '👅'),
  w('bajanna', 'बजाना', 'To Play (Instrument)', 'actions', '🎸'),
  w('banna', 'बनना', 'To Become / Make', 'actions', '🔨'),
  w('todna', 'तोड़ना', 'To Break', 'actions', '💔'),
  w('jodna', 'जोड़ना', 'To Join / Add', 'actions', '🧩'),
  w('seena', 'सीना', 'To Sew', 'actions', '🪡'),
  w('bunana', 'बुनना', 'To Knit / Weave', 'actions', '🧶'),
  w('rangna', 'रंगना', 'To Paint / Color', 'actions', '🎨'),
  w('chamakna', 'चमकना', 'To Shine', 'actions', '✨'),
  w('jalna', 'जलना', 'To Burn', 'actions', '🔥'),
  w('bujhana', 'बुझाना', 'To Extinguish', 'actions', '🧯'),
  w('bahna', 'बहना', 'To Flow', 'actions', '🌊'),
  w('barasna', 'बरसना', 'To Rain / Pour', 'actions', '🌧️'),
  w('thirakna', 'थिरकना', 'To Sway / Tap', 'actions', '💃'),
  w('ghoomna', 'घूमना', 'To Roam / Travel', 'actions', '🧭'),
  w('lotna', 'लौटना', 'To Return', 'actions', '🔙'),
  w('rukna_wait', 'इंतज़ार करना', 'To Wait', 'actions', '⏳'),
  w('madad_karna', 'मदद करना', 'To Help', 'actions', '🤝'),
  w('raksha_karna', 'रक्षा करना', 'To Protect', 'actions', '🛡️'),
  w('pooja_karna', 'पूजा करना', 'To Worship', 'actions', '🙏'),
  w('namaste_karna', 'नमस्ते करना', 'To Greet', 'actions', '🙏'),
  w('shukriya_kahna', 'धन्यवाद कहना', 'To Thank', 'actions', '💐'),
  w('maaf_karna', 'माफ़ करना', 'To Forgive', 'actions', '🤝'),
  w('pyaar_karna', 'प्यार करना', 'To Love', 'actions', '❤️'),
  w('ladna', 'लड़ना', 'To Fight', 'actions', '🤺'),
  w('jeetna', 'जीतना', 'To Win', 'actions', '🏆'),
  w('haarna', 'हारना', 'To Lose (Defeat)', 'actions', '🥈'),
  w('bhedna', 'बांटना', 'To Share / Distribute', 'actions', '🍰'),
  w('khareedna', 'खरीदना', 'To Buy', 'actions', '🛍️'),
  w('bechna', 'बेचना', 'To Sell', 'actions', '🏷️'),
  w('kamaana', 'कमाना', 'To Earn', 'actions', '💰'),

  // ================= 12. ADJECTIVES & OPPOSITES (90) =================
  w('achha', 'अच्छा', 'Good', 'general', '👍'),
  w('bura', 'बुरा', 'Bad', 'general', '👎'),
  w('sundar', 'सुंदर', 'Beautiful', 'general', '🌸'),
  w('bada', 'बड़ा', 'Big / Large', 'general', '🐘'),
  w('chhota', 'छोटा', 'Small / Tiny', 'general', '🐜'),
  w('lamba', 'लंबा', 'Tall / Long', 'general', '🦒'),
  w('naata', 'नाटा', 'Short (Height)', 'general', '🌱'),
  w('mota', 'मोटा', 'Fat / Thick', 'general', '🦛'),
  w('patla', 'पतला', 'Thin / Lean', 'general', '🪡'),
  w('bhaari', 'भारी', 'Heavy', 'general', '🏋️'),
  w('halka', 'हल्का', 'Light (Weight)', 'general', '🪶'),
  w('tez', 'तेज़', 'Fast / Sharp', 'general', '⚡'),
  w('dheema', 'धीमा', 'Slow', 'general', '🐢'),
  w('garam', 'गरम', 'Hot / Warm', 'general', '♨️'),
  w('thanda', 'ठंडा', 'Cold / Chilled', 'general', '🧊'),
  w('meetha', 'मीठा', 'Sweet', 'general', '🍯'),
  w('khatta', 'खट्टा', 'Sour', 'general', '🍋'),
  w('kadwa', 'कड़वा', 'Bitter', 'general', '💊'),
  w('teekha', 'तीखा', 'Spicy', 'general', '🌶️'),
  w('namkeen', 'नमकीन', 'Salty', 'general', '🧂'),
  w('saaf', 'साफ़', 'Clean / Tidy', 'general', '✨'),
  w('ganda', 'गंदा', 'Dirty', 'general', '🗑️'),
  w('naya', 'नया', 'New', 'general', '🆕'),
  w('purana', 'पुराना', 'Old', 'general', '🏛️'),
  w('geela', 'गीला', 'Wet', 'general', '💧'),
  w('sookha', 'सूखा', 'Dry', 'general', '🏜️'),
  w('kadak', 'कड़ा / सख़्त', 'Hard', 'general', '🪨'),
  w('naram', 'नरम', 'Soft', 'general', '🪶'),
  w('khurdura', 'खुरदुरा', 'Rough', 'general', '🪵'),
  w('chikna', 'चिकना', 'Smooth', 'general', '🧈'),
  w('seedha', 'सीधा', 'Straight', 'general', '📏'),
  w('tedha', 'टेढ़ा', 'Bent / Crooked', 'general', '〰️'),
  w('gol', 'गोल', 'Round / Circle', 'general', '⚪'),
  w('chaukor', 'चौकोर', 'Square', 'general', '⏹️'),
  w('tikona', 'तिकोना', 'Triangle', 'general', '🔺'),
  w('chouda', 'चौड़ा', 'Wide / Broad', 'general', '↔️'),
  w('sankra', 'सँकरा', 'Narrow', 'general', '🤏'),
  w('gehra', 'गहरा', 'Deep', 'general', '🕳️'),
  w('ubhla', 'उथला', 'Shallow', 'general', '🛶'),
  w('khula', 'खुला', 'Open', 'general', '📖'),
  w('band', 'बंद', 'Closed', 'general', '📕'),
  w('bhara', 'भरा हुआ', 'Full', 'general', '🥛'),
  w('khaali', 'खाली', 'Empty', 'general', '🫙'),
  w('zameen', 'सस्ता', 'Cheap', 'general', '🏷️'),
  w('mehanga', 'महँगा', 'Expensive', 'general', '💎'),
  w('ameer', 'अमीर', 'Rich', 'general', '💰'),
  w('gareeb', 'ग़रीब', 'Poor', 'general', '🤲'),
  w('asli', 'असली', 'Real / Genuine', 'general', '💯'),
  w('nakli', 'नकली', 'Fake', 'general', '🎭'),
  w('sach', 'सच', 'Truth', 'general', '🕊️'),
  w('jhooth', 'झूठ', 'Lie', 'general', '🤥'),
  w('shant', 'शांत', 'Quiet / Calm', 'general', '🤫'),
  w('shor', 'शोर', 'Noisy', 'general', '📢'),
  w('sukhi', 'सुखी', 'Happy', 'general', '😊'),
  w('dukhi', 'दुखी', 'Sad', 'general', '😢'),
  w('balwan', 'बलवान', 'Strong', 'general', '💪'),
  w('kamzor', 'कमज़ोर', 'Weak', 'general', '🥀'),
  w('chatur', 'चतुर', 'Clever', 'general', '🦊'),
  w('buddhimaan', 'बुद्धिमान', 'Wise', 'general', '🦉'),
  w('moorkh', 'मूर्ख', 'Foolish', 'general', '🤪'),
  w('sahasi', 'साहसी', 'Brave', 'general', '🦁'),
  w('darpok', 'डरपोक', 'Timid / Coward', 'general', '🐭'),
  w('dayalu', 'दयालु', 'Kind', 'general', '💖'),
  w('kathor', 'कठोर', 'Harsh', 'general', '🗿'),
  w('sachha', 'सच्चा', 'Truthful', 'general', '🕊️'),
  w('imaandar', 'ईमानदार', 'Honest', 'general', '🤝'),
  w('mehnati', 'मेहनती', 'Hardworking', 'general', '🐝'),
  w('aalsi', 'आलसी', 'Lazy', 'general', '🦥'),
  w('pyasa', 'प्यासा', 'Thirsty', 'general', '🥤'),
  w('bhookha', 'भूखा', 'Hungry', 'general', '🍽️'),
  w('swadisht', 'स्वादिष्ट', 'Delicious', 'general', '😋'),
  w('taaza', 'ताज़ा', 'Fresh', 'general', '🌿'),
  w('baasi', 'बासी', 'Stale', 'general', '🍞'),
  w('paka', 'पका हुआ', 'Ripe / Cooked', 'general', '🥭'),
  w('kacha', 'कच्चा', 'Raw / Unripe', 'general', '🍏'),
  w('shuddh', 'शुद्ध', 'Pure', 'general', '✨'),
  w('milavati', 'मिलावटी', 'Adulterated', 'general', '🧪'),
  w('aasan', 'आसान', 'Easy', 'general', '👌'),
  w('mushkil', 'मुश्किल', 'Difficult', 'general', '🧩'),
  w('sambhav', 'संभव', 'Possible', 'general', '🎯'),
  w('asambhav', 'असंभव', 'Impossible', 'general', '🚫'),
  w('sahi', 'सही', 'Correct / Right', 'general', '✅'),
  w('galat', 'गलत', 'Wrong / False', 'general', '❌'),
  w('surakshit', 'सुरक्षित', 'Safe', 'general', '🛡️'),
  w('khatarnak', 'खतरनाक', 'Dangerous', 'general', '⚠️'),
  w('khushbu', 'खुशबूदार', 'Fragrant', 'general', '🌸'),
  w('badboo', 'बदबूदार', 'Stinky', 'general', '🦨'),
  w('chamakdar', 'चमकदार', 'Shiny', 'general', '💎'),
  w('dhundhla', 'धुंधला', 'Blurry / Dim', 'general', '🌫️'),

  // ================= 13. PLACES & CITY (50) =================
  w('baazaar', 'बाज़ार', 'Market', 'places', '🏪'),
  w('dukaan', 'दुकान', 'Shop / Store', 'places', '🏬'),
  w('mall', 'मॉल', 'Shopping Mall', 'places', '🛍️'),
  w('bagicha', 'बगीचा', 'Garden / Park', 'places', '🏡'),
  w('park', 'उद्यान / पार्क', 'Park', 'places', '🌳'),
  w('mandir', 'मंदिर', 'Temple', 'places', '🛕'),
  w('masjid', 'मस्जिद', 'Mosque', 'places', '🕌'),
  w('gurudwara', 'गुरुद्वारा', 'Gurudwara', 'places', '🛕'),
  w('girjaghar', 'गिरजाघर', 'Church', 'places', '⛪'),
  w('aspatal', 'अस्पताल', 'Hospital', 'places', '🏥'),
  w('dawa_dukaan', 'दवाखाना', 'Pharmacy', 'places', '💊'),
  w('dakghar', 'डाकघर', 'Post Office', 'places', '📮'),
  w('police_thana', 'पुलिस थाना', 'Police Station', 'places', '👮'),
  w('bank', 'बैंक', 'Bank', 'places', '🏦'),
  w('hotel', 'होटल', 'Hotel / Restaurant', 'places', '🏨'),
  w('dhaba', 'ढाबा', 'Roadside Diner', 'places', '🍲'),
  w('bhavan', 'भवन', 'Building / Mansion', 'places', '🏛️'),
  w('mahal', 'महल', 'Palace', 'places', '🏰'),
  w('qila', 'किला', 'Fort', 'places', '🏯'),
  w('gaav', 'गाँव', 'Village', 'places', '🌾'),
  w('shahar', 'शहर', 'City / Town', 'places', '🏙️'),
  w('desh', 'देश', 'Country / Nation', 'places', '🇮🇳'),
  w('videsh', 'विदेश', 'Abroad', 'places', '✈️'),
  w('duniya', 'दुनिया', 'World', 'places', '🌍'),
  w('khet', 'खेत', 'Field / Farm', 'places', '🚜'),
  w('chidiya_ghar', 'चिड़ियाघर', 'Zoo', 'places', '🦁'),
  w('ajayabghar', 'अजायबघर', 'Museum', 'places', '🏛️'),
  w('cinema', 'सिनेमाघर', 'Cinema Hall', 'places', '🎬'),
  w('khelkood_sthal', 'स्टेडियम', 'Stadium', 'places', '🏟️'),
  w('pulw', 'पुल', 'Bridge', 'places', '🌉'),
  w('gali_mohalla', 'मोहल्ला', 'Neighborhood', 'places', '🏘️'),
  w('chauraha_place', 'चौक', 'Town Square', 'places', '⛲'),
  w('karkhana', 'कारख़ाना', 'Factory', 'places', '🏭'),
  w('godam', 'गोदाम', 'Warehouse', 'places', '📦'),
  w('karyalaya', 'कार्यालय', 'Office', 'places', '🏢'),
  w('adalat', 'अदालत', 'Court', 'places', '⚖️'),
  w('jail', 'जेल', 'Prison', 'places', '⛓️'),
  w('shala', 'पाठशाला', 'Schoolhouse', 'places', '🏫'),
  w('vishvavidyalaya', 'विश्वविद्यालय', 'University', 'places', '🎓'),
  w('ashram', 'आश्रम', 'Hermitage / Ashram', 'places', '🧘'),
  w('sarovar', 'सरोवर', 'Sacred Pool', 'places', '🪷'),
  w('ghat', 'घाट', 'Riverbank Steps', 'places', '🪜'),
  w('shmashan', 'श्मशान', 'Crematorium', 'places', '🔥'),
  w('kabristan', 'कब्रिस्तान', 'Graveyard', 'places', '🪦'),
  w('melap', 'मेला', 'Fair / Carnival', 'places', '🎡'),
  w('pradarshani', 'प्रदर्शनी', 'Exhibition', 'places', '🖼️'),
  w('chhatravas', 'छात्रावास', 'Hostel', 'places', '🏢'),
  w('dharamsala', 'धर्मशाला', 'Rest House', 'places', '🏨'),
  w('kendra', 'केंद्र', 'Center', 'places', '📍'),
  w('sthaan', 'स्थान', 'Place / Spot', 'places', '📌'),

  // ================= 14. TIME, SEASONS & CALENDAR (40) =================
  w('samay', 'समय', 'Time', 'time', '⏳'),
  w('ghanta', 'घंटा', 'Hour', 'time', '⌛'),
  w('minute', 'मिनट', 'Minute', 'time', '⏱️'),
  w('second', 'सेकंड', 'Second', 'time', '⏲️'),
  w('pal', 'पल', 'Moment', 'time', '✨'),
  w('aaj', 'आज', 'Today', 'time', '📅'),
  w('kal', 'कल', 'Tomorrow / Yesterday', 'time', '🗓️'),
  w('parson', 'परसों', 'Day After / Before', 'time', '📆'),
  w('ab', 'अब', 'Now', 'time', '⏰'),
  w('tab', 'तब', 'Then', 'time', '🕰️'),
  w('hamesha', 'हमेशा', 'Always', 'time', '♾️'),
  w('kabhi_nahi', 'कभी नहीं', 'Never', 'time', '🚫'),
  w('hafte', 'सप्ताह', 'Week', 'time', '📅'),
  w('mahina', 'महीना', 'Month', 'time', '🗓️'),
  w('saal', 'साल / वर्ष', 'Year', 'time', '🎆'),
  w('somwar', 'सोमवार', 'Monday', 'time', '🌙'),
  w('mangalwar', 'मंगलवार', 'Tuesday', 'time', '🔴'),
  w('budhwar', 'बुधवार', 'Wednesday', 'time', '🟢'),
  w('guruwar', 'गुरुवार', 'Thursday', 'time', '🟡'),
  w('shukrawar', 'शुक्रवार', 'Friday', 'time', '⚪'),
  w('shaniwar', 'शनिवार', 'Saturday', 'time', '🪐'),
  w('raviwar', 'रविवार', 'Sunday', 'time', '☀️'),
  w('mausam', 'मौसम', 'Weather / Season', 'time', '⛅'),
  w('ritu', 'ऋतु', 'Season', 'time', '🍂'),
  w('garmi', 'गर्मी', 'Summer', 'time', '☀️'),
  w('sardi', 'सर्दी', 'Winter', 'time', '❄️'),
  w('barsat', 'बरसात', 'Monsoon / Rainy', 'time', '🌧️'),
  w('vasant', 'बसंत', 'Spring', 'time', '🌸'),
  w('patjhad', 'पतझड़', 'Autumn', 'time', '🍁'),
  w('shishir', 'शिशिर', 'Late Winter', 'time', '🥶'),
  w('tyohar', 'त्यौहार', 'Festival', 'time', '🎉'),
  w('utsav', 'उत्सव', 'Celebration', 'time', '🎊'),
  w('janmadin', 'जन्मदिन', 'Birthday', 'time', '🎂'),
  w('diwali', 'दीपावली', 'Diwali', 'time', '🪔'),
  w('holi', 'होली', 'Holi', 'time', '🎨'),
  w('eid', 'ईद', 'Eid', 'time', '🌙'),
  w('christmas', 'क्रिसमस', 'Christmas', 'time', '🎄'),
  w('navvarsh', 'नया साल', 'New Year', 'time', '🎆'),
  w('raksha_bandhan', 'रक्षाबंधन', 'Rakhi Festival', 'time', '🧵'),
  w('swatantrata_diwas', 'स्वतंत्रता दिवस', 'Independence Day', 'time', '🇮🇳'),

  // ================= 15. EMOTIONS, MIND & VALUES (50) =================
  w('khushi', 'खुशी', 'Happiness / Joy', 'general', '😊'),
  w('anand', 'आनंद', 'Delight / Bliss', 'general', '😃'),
  w('dukh', 'दुख', 'Sorrow / Grief', 'general', '😢'),
  w('rona_bhav', 'उदासी', 'Sadness', 'general', '😔'),
  w('gussa', 'गुस्सा', 'Anger / Rage', 'general', '😡'),
  w('krodh', 'क्रोध', 'Wrath', 'general', '🤬'),
  w('dar', 'डर', 'Fear', 'general', '😨'),
  w('bhaya', 'भय', 'Fright / Dread', 'general', '😱'),
  w('shanti', 'शांति', 'Peace', 'general', '🕊️'),
  w('pyar', 'प्यार', 'Love', 'general', '❤️'),
  w('prem', 'प्रेम', 'Affection / Love', 'general', '💖'),
  w('dostee', 'दोस्ती', 'Friendship', 'general', '🤝'),
  w('daya', 'दया', 'Compassion / Mercy', 'general', '🤲'),
  w('kripa', 'कृपा', 'Grace / Kindness', 'general', '🙏'),
  w('aashirwaad', 'आशीर्वाद', 'Blessing', 'general', '✨'),
  w('dheeraj', 'धीरज', 'Patience', 'general', '🧘'),
  w('sahas', 'साहस', 'Courage', 'general', '🦁'),
  w('himmat', 'हिम्मत', 'Bravery / Spirit', 'general', '💪'),
  w('vishwas', 'विश्वास', 'Faith / Trust', 'general', '🤝'),
  w('bharosa', 'भरोसा', 'Reliance / Trust', 'general', '🤞'),
  w('aasha', 'आशा', 'Hope', 'general', '🌟'),
  w('sapna', 'सपना', 'Dream', 'general', '💭'),
  w('chinta', 'चिंता', 'Worry / Anxiety', 'general', '😟'),
  w('hairani', 'हैरानी', 'Surprise / Wonder', 'general', '😲'),
  w('sharm', 'शर्म', 'Shyness / Shame', 'general', '😳'),
  w('garva', 'गर्व', 'Pride (Noble)', 'general', '🦚'),
  w('ghamand', 'घमंड', 'Arrogance / Ego', 'general', '😤'),
  w('sukoon', 'सुकून', 'Tranquility', 'general', '😌'),
  w('utsaha', 'उत्साह', 'Enthusiasm / Zeal', 'general', '🤩'),
  w('aashcharya', 'आश्चर्य', 'Amazement', 'general', '✨'),
  w('nafrat', 'नफ़रत', 'Hatred', 'general', '💔'),
  w('jalan', 'जलन', 'Jealousy', 'general', '😒'),
  w('lobh', 'लोभ', 'Greed', 'general', '🤑'),
  w('dharma', 'धर्म', 'Duty / Righteousness', 'general', '⚖️'),
  w('nyay', 'न्याय', 'Justice', 'general', '⚖️'),
  w('satya', 'सत्य', 'Truth (Pure)', 'general', '🕊️'),
  w('ahimsa', 'अहिंसा', 'Non-violence', 'general', '🕊️'),
  w('seva', 'सेवा', 'Service / Help', 'general', '🤲'),
  w('daan', 'दान', 'Charity / Donation', 'general', '🎁'),
  w('namrata', 'नम्रता', 'Humility', 'general', '🙇'),
  w('aadar', 'आदर', 'Respect / Honor', 'general', '🙏'),
  w('samman', 'सम्मान', 'Dignity', 'general', '🎖️'),
  w('lajja', 'लज्जा', 'Modesty', 'general', '🙈'),
  w('teerth', 'तीर्थ', 'Pilgrimage', 'general', '🕉️'),
  w('bhakti', 'भक्ति', 'Devotion', 'general', '🪔'),
  w('gyan', 'ज्ञान', 'Knowledge / Wisdom', 'general', '💡'),
  w('vidya', 'विद्या', 'Learning / Education', 'general', '📚'),
  w('buddhi', 'बुद्धि', 'Intellect', 'general', '🧠'),
  w('mann', 'मन', 'Heart / Mind', 'general', '🧘'),
  w('aatma', 'आत्मा', 'Soul / Spirit', 'general', '✨'),

  // ================= 16. NUMBERS & QUANTITY (50) =================
  w('ek', 'एक', 'One (1)', 'general', '1️⃣'),
  w('do', 'दो', 'Two (2)', 'general', '2️⃣'),
  w('teen', 'तीन', 'Three (3)', 'general', '3️⃣'),
  w('chaar', 'चार', 'Four (4)', 'general', '4️⃣'),
  w('paanch', 'पाँच', 'Five (5)', 'general', '5️⃣'),
  w('chhah', 'छह', 'Six (6)', 'general', '6️⃣'),
  w('saat', 'सात', 'Seven (7)', 'general', '7️⃣'),
  w('aath', 'आठ', 'Eight (8)', 'general', '8️⃣'),
  w('nau', 'नौ', 'Nine (9)', 'general', '9️⃣'),
  w('das', 'दस', 'Ten (10)', 'general', '🔟'),
  w('gyarah', 'ग्यारह', 'Eleven (11)', 'general', '🔢'),
  w('barah', 'बारह', 'Twelve (12)', 'general', '🔢'),
  w('terah', 'तेरह', 'Thirteen (13)', 'general', '🔢'),
  w('chaudah', 'चौदह', 'Fourteen (14)', 'general', '🔢'),
  w('pandrah', 'पंद्रह', 'Fifteen (15)', 'general', '🔢'),
  w('solah', 'सोलह', 'Sixteen (16)', 'general', '🔢'),
  w('satrah', 'सत्रह', 'Seventeen (17)', 'general', '🔢'),
  w('atharah', 'अट्ठारह', 'Eighteen (18)', 'general', '🔢'),
  w('unnees', 'उन्नीस', 'Nineteen (19)', 'general', '🔢'),
  w('bees', 'बीस', 'Twenty (20)', 'general', '🔢'),
  w('tees', 'तीस', 'Thirty (30)', 'general', '🔢'),
  w('chalis', 'चालीस', 'Forty (40)', 'general', '🔢'),
  w('pachaas', 'पचास', 'Fifty (50)', 'general', '🔢'),
  w('saath', 'साठ', 'Sixty (60)', 'general', '🔢'),
  w('sattar', 'सत्तर', 'Seventy (70)', 'general', '🔢'),
  w('assi', 'अस्सी', 'Eighty (80)', 'general', '🔢'),
  w('nabbe', 'नब्बे', 'Ninety (90)', 'general', '🔢'),
  w('sau', 'सौ', 'Hundred (100)', 'general', '💯'),
  w('hazaar', 'हज़ार', 'Thousand (1,000)', 'general', '💰'),
  w('laakh', 'लाख', 'Lakh (100,000)', 'general', '💎'),
  w('crore', 'करोड़', 'Crore (10,000,000)', 'general', '👑'),
  w('aadha', 'आधा', 'Half (1/2)', 'general', '🌗'),
  w('pau', 'पाव / चौथाई', 'Quarter (1/4)', 'general', '🌘'),
  w('pona', 'पौना', 'Three-Quarters (3/4)', 'general', '🌖'),
  w('sawa', 'सवा', 'One and a Quarter', 'general', '➕'),
  w('dhai', 'ढाई', 'Two and a Half', 'general', '➕'),
  w('dedh', 'डेढ़', 'One and a Half', 'general', '➕'),
  w('saare', 'सभी / सारे', 'All / Entire', 'general', '🌐'),
  w('kuch', 'कुछ', 'Some / A few', 'general', '🤏'),
  w('bahut', 'बहुत', 'A lot / Many', 'general', '📦'),
  w('thoda', 'थोड़ा', 'A little', 'general', '🤏'),
  w('adhik', 'अधिक', 'More / Excess', 'general', '➕'),
  w('kam', 'कम', 'Less / Fewer', 'general', '➖'),
  w('barabar', 'बराबर', 'Equal', 'general', '🟰'),
  w('dugna', 'दुगना', 'Double', 'general', '✖️'),
  w('pehla', 'पहला', 'First', 'general', '🥇'),
  w('doosra', 'दूसरा', 'Second', 'general', '🥈'),
  w('teesra', 'तीसरा', 'Third', 'general', '🥉'),
  w('aakhri', 'आख़िरी', 'Last / Final', 'general', '🏁'),
  w('shunya', 'शून्य', 'Zero (0)', 'general', '0️⃣'),

  // ================= 17. DAILY ITEMS, OBJECTS & TOOLS (50) =================
  w('gend', 'गेंद', 'Ball', 'general', '⚽'),
  w('khilona', 'खिलौना', 'Toy', 'general', '🧸'),
  w('gudiya', 'गुड़िया', 'Doll', 'general', '🪆'),
  w('patang', 'पतंग', 'Kite', 'general', '🪁'),
  w('firki', 'फिरकी', 'Pinwheel', 'general', '🌀'),
  w('lattu', 'लट्टू', 'Spinning Top', 'general', '🪀'),
  w('rassa', 'रस्सी', 'Rope', 'general', '🪢'),
  w('jhula', 'झूला', 'Swing', 'general', '🎪'),
  w('pasa', 'पासा', 'Dice', 'general', '🎲'),
  w('taash', 'ताश', 'Cards', 'general', '🃏'),
  w('carrom', 'कैरम', 'Carrom', 'general', '🎯'),
  w('shatranj', 'शतरंज', 'Chess', 'general', '♟️'),
  w('bat', 'बल्ला', 'Cricket Bat', 'general', '🏏'),
  w('wicket', 'विकेट', 'Wicket / Stumps', 'general', '🏏'),
  w('jaal', 'जाल', 'Net', 'general', '🥅'),
  w('hathoda', 'हथौड़ा', 'Hammer', 'general', '🔨'),
  w('kulhadi', 'कुल्हाड़ी', 'Axe', 'general', '🪓'),
  w('aari', 'आरी', 'Saw', 'general', '🪚'),
  w('pechkas', 'पेचकस', 'Screwdriver', 'general', '🪛'),
  w('plas', 'पलाश / प्लास', 'Pliers', 'general', '🔧'),
  w('paana', 'पाना', 'Wrench / Spanner', 'general', '🔧'),
  w('keel', 'कील', 'Nail', 'general', '🔩'),
  w('pech', 'पेंच', 'Screw', 'general', '🔩'),
  w('chammach_loha', 'खुरपी', 'Trowel', 'general', '🪴'),
  w('faawda', 'फावड़ा', 'Shovel / Spade', 'general', '⛏️'),
  w('kudal', 'कुदाल', 'Pickaxe', 'general', '⛏️'),
  w('dhanush', 'धनुष', 'Bow', 'general', '🏹'),
  w('teer', 'तीर', 'Arrow', 'general', '🏹'),
  w('talwar', 'तलवार', 'Sword', 'general', '⚔️'),
  w('dhaal', 'ढाल', 'Shield', 'general', '🛡️'),
  w('bandook', 'बंदूक', 'Gun / Rifle', 'general', '🔫'),
  w('top', 'तोप', 'Cannon', 'general', '💣'),
  w('sikka', 'सिक्का', 'Coin', 'general', '🪙'),
  w('not', 'नोट / रुपया', 'Currency Note', 'general', '💵'),
  w('paisa', 'पैसा', 'Money', 'general', '💰'),
  w('batua', 'बटुआ', 'Wallet / Purse', 'general', '👛'),
  w('khazana', 'ख़ज़ाना', 'Treasure', 'general', '👑'),
  w('tala_chabi', 'ताला चाबी', 'Lock and Key', 'general', '🔐'),
  w('durbin', 'दूरबीन', 'Binoculars', 'general', '🔭'),
  w('sookshmadarshi', 'सूक्ष्मदर्शी', 'Microscope', 'general', '🔬'),
  w('chumbak', 'चुंबक', 'Magnet', 'general', '🧲'),
  w('battery', 'बैटरी', 'Battery / Cell', 'general', '🔋'),
  w('torch', 'टॉर्च', 'Flashlight', 'general', '🔦'),
  w('mombatti', 'मोमबत्ती', 'Candle', 'general', '🕯️'),
  w('diya', 'दीया', 'Earthen Lamp', 'general', '🪔'),
  w('machis', 'माचिस', 'Matchbox', 'general', '🪵'),
  w('agarbatti', 'अगरबत्ती', 'Incense Stick', 'general', '🪔'),
  w('shankh', 'शंख', 'Conch Shell', 'general', '🐚'),
  w('dholak', 'ढोलक', 'Drum (Dholak)', 'general', '🪘'),
  w('bansuri', 'बांसुरी', 'Flute', 'general', '🪈'),
];

console.log(`Prepared ${words.length} unique words.`);

console.log(`Total count of words: ${words.length}`);

// Generate Dart code
const dartCode = `import '../models/common_word.dart';

class AppData {
  static const List<CommonWord> words = [
${words.map(item => `    CommonWord(id: '${item.id}', hindi: '${item.hindi}', english: '${item.english.replace(/'/g, "\\'")}', category: '${item.category}', emoji: '${item.emoji}', hindiAudio: '${item.hindiAudio}', englishAudio: '${item.englishAudio}'),`).join('\n')}
  ];
}
`;

const targetFile = path.join(__dirname, 'hindi_voice_part_two', '29_hindi_common_words', 'lib', 'data', 'app_data.dart');
fs.writeFileSync(targetFile, dartCode, 'utf8');
console.log(`Successfully wrote ${words.length} words to ${targetFile}!`);

