const Map<String, String> enStrings = {
  'app_title': 'Hindi Reading Notebook',
  'subtitle': 'Progressive reading ladder from letters to sentences (1000+ items)',
  'start_learning': 'Learn Reading',
  'practice': 'Reading Practice',
  'progress': 'Progress',
  'settings': 'Settings',
  'level': 'Level',
  'completed_items': 'Completed Lessons',
  'language': 'Language',
  'sound': 'Sound',
  'reset_progress': 'Reset Progress',
  'about': 'About App',
  'about_desc': 'Progressive Hindi reading notebook with 1000+ lessons 100% offline.',
  'listen': 'Listen',
  'read_aloud': 'Read Aloud',
  'breakdown': 'Syllable Breakdown',
  'level_1_title': 'Level 1: Alphabet & Syllables',
  'level_2_title': 'Level 2: 2-Letter Words',
  'level_3_title': 'Level 3: 3-Letter Words',
  'level_4_title': 'Level 4: 4-Letter & Phrases',
  'level_5_title': 'Level 5: Sentences & Stories',
  'search_hint': 'Search letter, word or sentence...',
  'congratulations': 'Well done! Reading complete!',
};
