const Map<String, String> hiStrings = {
  'app_title': 'हिंदी पठन नोटबुक',
  'subtitle': 'अक्षर से वाक्य तक पढ़ने का सफर (1000+ पाठ)',
  'start_learning': 'पढ़ना सीखें',
  'practice': 'पठन अभ्यास',
  'progress': 'प्रगति',
  'settings': 'सेटिंग्स',
  'level': 'स्तर',
  'completed_items': 'पढ़े गए पाठ',
  'language': 'भाषा',
  'sound': 'ध्वनि',
  'reset_progress': 'प्रगति रीसेट करें',
  'about': 'ऐप के बारे में',
  'about_desc': '1000+ प्रामाणिक पाठों से हिंदी पढ़ना सिखाने वाली नोटबुक 100% ऑफ़लाइन।',
  'listen': 'सुनें',
  'read_aloud': 'बोलकर पढ़ें',
  'breakdown': 'अक्षर विच्छेद',
  'level_1_title': 'स्तर १: वर्णमाला व बारहखड़ी',
  'level_2_title': 'स्तर २: दो अक्षर वाले सरल शब्द',
  'level_3_title': 'स्तर ३: तीन अक्षर वाले शब्द',
  'level_4_title': 'स्तर ४: चार अक्षर व वाक्यांश',
  'level_5_title': 'स्तर ५: पठन वाक्य व कहानियाँ',
  'search_hint': 'अक्षर, शब्द या वाक्य खोजें...',
  'congratulations': 'शाबाश! पठन अभ्यास पूरा हुआ!',
};
