const Map<String, String> enStrings = {
  'app_title': 'Hindi Vocabulary Notebook',
  'subtitle': '1,000+ words across 37 rich categories with crystal clear voice',
  'start_learning': 'Learn Vocabulary',
  'practice': 'Vocabulary Practice',
  'progress': 'Learning Progress',
  'settings': 'Settings & Audio',
  'all': 'All Words',
  'animals': 'Animals & Birds',
  'fruits': 'Sweet Fruits',
  'vegetables': 'Vegetables',
  'body': 'Body Parts',
  'nature': 'Nature & Elements',
  'family': 'Family & Relations',
  'colors': 'Vibrant Colors',
  'school': 'School & Studies',
  'house': 'Home & Furniture',
  'food': 'Food & Sweets',
  'clothes': 'Clothes & Wear',
  'vehicles': 'Vehicles & Transport',
  'professions': 'Jobs & Professions',
  'numbers': 'Hindi Numbers',
  'actions': 'Action Verbs',
  'emotions': 'Feelings & Emotions',
  'places': 'Places & Landmarks',
  'flowers': 'Flowers',
  'festivals': 'Festivals & Culture',
  'opposites': 'Opposite Words',
  'adjectives': 'Adjectives & Quality',
  'spices': 'Spices & Flavors',
  'instruments': 'Musical Instruments',
  'materials': 'Materials & Metals',
  'kitchen': 'Kitchen & Utensils',
  'sports': 'Sports & Fitness',
  'time': 'Time & Days',
  'tech': 'Tech & Science',
  'geography': 'Geography & Landforms',
  'daily': 'Daily Phrases',
  'shopping': 'Shopping & Market',
  'health': 'Health & Medicine',
  'arts': 'Arts & Culture',
  'office': 'Work & Office',
  'environment': 'Environment & Climate',
  'completed_items': 'Mastered Words',
  'search_hint': 'Search Hindi or English word...',
  'words_count': 'Total Words',
  'categories_count': 'Categories',
  'mastered': 'Mastered',
  'listen_hi': 'Listen in Hindi',
  'listen_en': 'Listen in English',
  'voice_test': 'Voice Test',
  'voice_test_desc': 'Test Hindi & English speech synthesis',
  'test_hi_spoken': 'नमस्ते! हिंदी शब्दकोश नोटबुक में आपका स्वागत है।',
  'test_en_spoken': 'Welcome to Hindi Vocabulary Notebook!',
  'language': 'Language',
  'sound': 'Voice & Sound Effects',
  'reset_progress': 'Reset Progress',
  'reset_confirm': 'Are you sure you want to reset all your learning progress?',
  'cancel': 'Cancel',
  'confirm': 'Yes, Reset',
  'about': 'About App',
  'about_desc': '1,000+ Illustrated vocabulary items with instant bilingual audio voice & speech synthesis.',
  'congratulations': 'Great job! You mastered a new word! 🎉',
  'all_done': 'Awesome! You mastered all words!',
};
