const Map<String, String> hiStrings = {
  'app_title': 'हिंदी शब्दकोश नोटबुक',
  'subtitle': '37+ श्रेणियों में 1,000+ समृद्ध सचित्र शब्दावली व स्पष्ट आवाज़',
  'start_learning': 'शब्दावली सीखें',
  'practice': 'शब्दावली अभ्यास',
  'progress': 'सीखने की प्रगति',
  'settings': 'सेटिंग्स व ध्वनि',
  'all': 'सभी शब्द',
  'animals': 'पशु व पक्षी',
  'fruits': 'मीठे फल',
  'vegetables': 'सब्जियाँ',
  'body': 'शरीर के अंग',
  'nature': 'प्रकृति व नदियाँ',
  'family': 'परिवार व रिश्ते',
  'colors': 'रंग-बिरंगे रंग',
  'school': 'विद्यालय व पढ़ाई',
  'house': 'घर व सामान',
  'food': 'भोजन व मिष्ठान',
  'clothes': 'वस्त्र व आभूषण',
  'vehicles': 'यातायात वाहन',
  'professions': 'व्यवसाय व कार्य',
  'numbers': 'हिंदी संख्याएँ',
  'actions': 'क्रियाएँ व कर्म',
  'emotions': 'भाव व भावनाएँ',
  'places': 'स्थान व स्थल',
  'flowers': 'सुगंधित फूल',
  'festivals': 'त्यौहार व पर्व',
  'opposites': 'विलोम शब्द',
  'adjectives': 'विशेषण शब्द',
  'spices': 'मसाले व स्वाद',
  'instruments': 'वाद्य यंत्र',
  'materials': 'धातु व पदार्थ',
  'kitchen': 'रसोई के बर्तन',
  'sports': 'खेल व व्यायाम',
  'time': 'समय व दिन',
  'tech': 'तकनीक व विज्ञान',
  'geography': 'भूगोल व भूखंड',
  'daily': 'दैनिक बोलचाल',
  'shopping': 'बाज़ार व खरीदारी',
  'health': 'स्वास्थ्य व चिकित्सा',
  'arts': 'कला व संगीत',
  'office': 'दफ़्तर व कार्य',
  'environment': 'पर्यावरण व मौसम',
  'completed_items': 'कंठस्थ किए गए शब्द',
  'search_hint': 'हिंदी या अंग्रेजी शब्द खोजें...',
  'words_count': 'कुल शब्द',
  'categories_count': 'श्रेणियाँ',
  'mastered': 'कंठस्थ',
  'listen_hi': 'हिंदी में सुनें',
  'listen_en': 'अंग्रेजी में सुनें',
  'voice_test': 'ध्वनि परीक्षण (Voice Test)',
  'voice_test_desc': 'हिंदी व अंग्रेजी वाणी की जांच करें',
  'test_hi_spoken': 'नमस्ते! हिंदी शब्दकोश नोटबुक में आपका स्वागत है।',
  'test_en_spoken': 'Welcome to Hindi Vocabulary Notebook!',
  'language': 'भाषा (Language)',
  'sound': 'आवाज़ व ध्वनि प्रभाव',
  'reset_progress': 'प्रगति रीसेट करें',
  'reset_confirm': 'क्या आप सचमुच अपनी प्रगति रीसेट करना चाहते हैं?',
  'cancel': 'रद्द करें',
  'confirm': 'हाँ, रीसेट करें',
  'about': 'ऐप के बारे में',
  'about_desc': '1,000+ सचित्र शब्दों व स्पष्ट दोहरी ध्वनि (Hindi & English Voice) के साथ समृद्ध शब्दावली ऐप।',
  'congratulations': 'शानदार! आपने नया शब्द सीख लिया! 🎉',
  'all_done': 'अद्भुत! आपने सभी शब्द सीख लिए!',
};
