const Map<String, String> enStrings = {
  'app_title': 'Hindi Word Cards',
  'subtitle': '1,000+ interactive 3D flip flashcards across 33+ categories',
  'start_learning': 'Flashcards Deck',
  'practice': 'Practice Cards',
  'progress': 'Progress Details',
  'settings': 'Settings & Audio',
  'tap_to_flip': 'Tap card to flip 👆',
  'completed_items': 'Mastered Cards',
  'language': 'Language',
  'sound': 'Voice & Sound',
  'reset_progress': 'Reset Progress',
  'reset_confirm': 'Are you sure you want to reset all your card progress?',
  'cancel': 'Cancel',
  'confirm': 'Yes, Reset',
  'about': 'About App',
  'about_desc': '1,000+ Illustrated 3D flip flashcards with bilingual Hindi & English speech synthesis.',
  'all': 'All Cards',
  'animals': 'Animals & Birds',
  'fruits': 'Sweet Fruits',
  'vegetables': 'Vegetables',
  'body': 'Body Parts',
  'nature': 'Nature & Elements',
  'house': 'Home & Furniture',
  'food': 'Food & Sweets',
  'clothes': 'Clothes & Wear',
  'vehicles': 'Vehicles & Transport',
  'professions': 'Jobs & Professions',
  'numbers': 'Numbers',
  'colors': 'Vibrant Colors',
  'actions': 'Actions & Verbs',
  'emotions': 'Feelings & Emotions',
  'school': 'School & Studies',
  'flowers': 'Flowers',
  'festivals': 'Festivals & Culture',
  'opposites': 'Opposite Words',
  'adjectives': 'Adjectives',
  'spices': 'Spices & Flavors',
  'instruments': 'Musical Instruments',
  'materials': 'Materials & Metals',
  'kitchen': 'Kitchen Utensils',
  'sports': 'Sports & Fitness',
  'time': 'Time & Calendar',
  'tech': 'Tech & Science',
  'geography': 'Geography & Landforms',
  'daily': 'Daily Phrases',
  'shopping': 'Shopping & Market',
  'health': 'Health & Medicine',
  'arts': 'Arts & Culture',
  'office': 'Office & Work',
  'environment': 'Environment & Climate',
  'search_hint': 'Search flashcard words...',
  'cards_count': 'Total Cards',
  'deck_mode': 'Deck Mode',
  'grid_mode': 'Grid Mode',
  'previous': 'Previous',
  'next': 'Next',
  'shuffle': 'Shuffle',
  'listen_hi': 'Listen Hindi',
  'listen_en': 'Listen English',
  'voice_test': 'Voice Test',
  'voice_test_desc': 'Test speech synthesis pronunciation',
};
