const Map<String, String> enStrings = {
  'app_title': 'Hindi Number Matching',
  'subtitle': 'Match numerals and words (1000+ items)',
  'start_learning': 'Matching Game',
  'practice': 'Practice',
  'progress': 'Progress',
  'settings': 'Settings',
  'prompt': 'Tap numeral and matching word ✨',
  'completed_items': 'Matched Pairs',
  'great_job': 'Great Match! 🎉',
  'try_again': 'Try Again 😊',
  'next': 'Next Level',
  'language': 'Language',
  'sound': 'Sound',
  'reset_progress': 'Reset Progress',
  'about': 'About App',
  'about_desc': '100% Offline Hindi number & word matching game (1000+ items).',
  'categories': 'Categories',
  'all_categories': 'All Categories',
  'streak': 'Streak',
  'score': 'Score',
  'accuracy': 'Accuracy',
  'total': 'Total',
  'done': 'Done',
  'mastery': 'Mastery',
  'round_cleared': 'Awesome! All pairs matched! 🌟',
};
