const Map<String, String> hiStrings = {
  'app_title': 'हिंदी अंक मिलान',
  'subtitle': 'अंक और शब्द को मिलाएँ (1000+ डेटा)',
  'start_learning': 'मिलान खेल',
  'practice': 'अभ्यास',
  'progress': 'प्रगति',
  'settings': 'सेटिंग्स',
  'prompt': 'संख्या और नाम को छूकर सही मिलान करें ✨',
  'completed_items': 'सफल मिलान',
  'great_job': 'शानदार मिलान! 🎉',
  'try_again': 'फिर कोशिश करें 😊',
  'next': 'अगला स्तर',
  'language': 'भाषा',
  'sound': 'ध्वनि',
  'reset_progress': 'प्रगति रीसेट करें',
  'about': 'ऐप के बारे में',
  'about_desc': 'हिंदी संख्या और शब्द मिलान खेल 100% ऑफ़लाइन (1000+ डेटा)।',
  'categories': 'श्रेणियाँ',
  'all_categories': 'सभी श्रेणियाँ',
  'streak': 'स्ट्राइक',
  'score': 'स्कोर',
  'accuracy': 'सटीकता',
  'total': 'कुल',
  'done': 'पूर्ण',
  'mastery': 'दक्षता',
  'round_cleared': 'शाबाश! सभी जोड़ियाँ मिल गईं! 🌟',
};
