
const Map<String, String> enStrings = {
  'app_title': 'Hindi Word Notebook',
  'subtitle': 'Write and practice words in your digital notebook',
  'start_learning': 'Open Notebook',
  'practice': 'Notebook Practice',
  'progress': 'Progress',
  'settings': 'Settings',
  'page': 'Page',
  'stamped': 'Mastered! 🌟',
  'mark_done': 'Mark Completed',
  'write_word': 'Writing Slate',
  'clear': 'Clear',
  'next_page': 'Next Page',
  'prev_page': 'Previous Page',
  'completed_items': 'Mastered Pages',
  'great_job': 'Great Job! 🎉',
  'try_again': 'Try Again 😊',
  'language': 'Language',
  'sound': 'Sound',
  'reset_progress': 'Reset Progress',
  'about': 'About App',
  'about_desc': 'Digital notebook experience for kids 100% offline.',
};
