
const Map<String, String> hiStrings = {
  'app_title': 'हिंदी शब्द नोटबुक',
  'subtitle': 'अपनी डिजिटल नोटबुक में नए शब्द लिखें',
  'start_learning': 'नोटबुक खोलें',
  'practice': 'नोटबुक अभ्यास',
  'progress': 'प्रगति',
  'settings': 'सेटिंग्स',
  'page': 'पृष्ठ',
  'stamped': 'सीखा गया! 🌟',
  'mark_done': 'सम्पन्न चिह्नित करें',
  'write_word': 'अभ्यास स्लेट',
  'clear': 'साफ़ करें',
  'next_page': 'अगला पृष्ठ',
  'prev_page': 'पिछला पृष्ठ',
  'completed_items': 'नोटबुक में पूर्ण पृष्ठ',
  'great_job': 'अद्भुत काम! 🎉',
  'try_again': 'फिर कोशिश करें 😊',
  'language': 'भाषा',
  'sound': 'ध्वनि',
  'reset_progress': 'प्रगति रीसेट करें',
  'about': 'ऐप के बारे में',
  'about_desc': 'बच्चों के लिए सुंदर डिजिटल नोटबुक 100% ऑफ़लाइन।',
};
