
const Map<String, String> enStrings = {
  'app_title': 'Hindi Common Words',
  'subtitle': 'Most frequently used daily Hindi words',
  'start_learning': 'Word Collection',
  'practice': 'Vocabulary Quiz',
  'progress': 'Progress',
  'settings': 'Settings',
  'all': 'All',
  'daily': 'Daily',
  'fruits': 'Fruits',
  'animals': 'Animals',
  'school': 'School',
  'nature': 'Nature',
  'body': 'Body',
  'family': 'Family',
  'home': 'Home',
  'clothes': 'Clothes',
  'vehicles': 'Vehicles',
  'food': 'Food',
  'actions': 'Actions',
  'places': 'Places',
  'time': 'Time',
  'general': 'General',
  'favorites': 'Favorites',
  'search_hint': 'Search words...',
  'completed_items': 'Learned Words',
  'total_score': 'Total Score',
  'great_job': 'Great Job! 🎉',
  'try_again': 'Try Again 😊',
  'next': 'Next',
  'language': 'Language',
  'sound': 'Sound',
  'sound_on': 'Sound On',
  'sound_off': 'Sound Off',
  'reset_progress': 'Reset Progress',
  'about': 'About App',
  'about_desc': '100% Offline common Hindi vocabulary for kids.',
};
