
const Map<String, String> hiStrings = {
  'app_title': 'हिंदी आम शब्द',
  'subtitle': 'रोज़मर्रा के सबसे ज़्यादा इस्तेमाल होने वाले शब्द',
  'start_learning': 'शब्द संग्रह',
  'practice': 'शब्दावली क्विज़',
  'progress': 'प्रगति',
  'settings': 'सेटिंग्स',
  'all': 'सभी',
  'daily': 'दैनिक',
  'fruits': 'फल',
  'animals': 'जानवर',
  'school': 'स्कूल',
  'nature': 'प्रकृति',
  'favorites': 'पसंदीदा',
  'search_hint': 'खोजें...',
  'completed_items': 'सीखे गए शब्द',
  'total_score': 'कुल अंक',
  'great_job': 'बहुत बढ़िया! 🎉',
  'try_again': 'फिर कोशिश करें 😊',
  'next': 'अगला',
  'language': 'भाषा',
  'sound': 'ध्वनि',
  'sound_on': 'ध्वनि चालू',
  'sound_off': 'ध्वनि बंद',
  'reset_progress': 'प्रगति रीसेट करें',
  'about': 'ऐप के बारे में',
  'about_desc': 'बच्चों के लिए 100% ऑफ़लाइन सामान्य हिंदी शब्दकोश।',
};
