const Map<String, String> enStrings = {
  'app_title': 'Hindi Number Recognition',
  'subtitle': 'Listen and recognize 1000+ Hindi numbers & words',
  'start_learning': 'Recognition Game',
  'practice': 'Quiz',
  'progress': 'Progress',
  'settings': 'Settings',
  'prompt': 'Which item did you hear? 🎧',
  'prompt_visual': 'Which item is this? Choose the correct option ✨',
  'great_job': 'Great Job! 🎉',
  'try_again': 'Try Again 😊',
  'next': 'Next',
  'previous': 'Previous',
  'completed_items': 'Recognized Numbers & Words',
  'language': 'Language',
  'sound': 'Sound',
  'reset_progress': 'Reset Progress',
  'about': 'About App',
  'about_desc': '100% Offline audio-based Hindi number & word recognition (1000+ items).',
  'all_categories': 'All Categories',
  'streak': 'Streak',
  'accuracy': 'Accuracy',
  'score': 'Score',
  'total_items': 'Total Items',
  'listen_again': 'Listen Again',
  'sound_mode': 'Listen & Identify 🎧',
  'text_mode': 'Look & Identify 👀',
  'categories': 'Categories',
  'total': 'Total',
  'done': 'Done',
  'mastery': 'Mastery',
};
