const Map<String, String> hiStrings = {
  'app_title': 'हिंदी अंक पहचान',
  'subtitle': 'आवाज़ सुनें और 1000+ संख्याएँ एवं शब्द पहचानें',
  'start_learning': 'अंक पहचान खेल',
  'practice': 'क्विज़',
  'progress': 'प्रगति',
  'settings': 'सेटिंग्स',
  'prompt': 'कौन सी संख्या सुनी? चुनो 🎧',
  'prompt_visual': 'यह कौन सा शब्द / संख्या है? सही उत्तर चुनो ✨',
  'great_job': 'बहुत बढ़िया! 🎉',
  'try_again': 'फिर कोशिश करें 😊',
  'next': 'अगला',
  'previous': 'पिछला',
  'completed_items': 'पहचाने गए अंक व शब्द',
  'language': 'भाषा',
  'sound': 'ध्वनि',
  'reset_progress': 'प्रगति रीसेट करें',
  'about': 'ऐप के बारे में',
  'about_desc': 'श्रवण आधारित हिंदी अंक व शब्द पहचान 100% ऑफ़लाइन (1000+ डेटा)।',
  'all_categories': 'सभी श्रेणियाँ',
  'streak': 'स्ट्राइक',
  'accuracy': 'सटीकता',
  'score': 'स्कोर',
  'total_items': 'कुल डेटा',
  'listen_again': 'फिर से सुनें',
  'sound_mode': 'सुनो और पहचानो 🎧',
  'text_mode': 'देखो और पहचानो 👀',
  'categories': 'श्रेणियाँ',
  'total': 'कुल',
  'done': 'पूर्ण',
  'mastery': 'दक्षता',
};
