const Map<String, String> enStrings = {
  'app_title': 'Hindi Practice Book',
  'subtitle': '1000+ words, letters, vowels & sentences practice',
  'start_learning': 'Open Workbook',
  'practice': 'Practice',
  'progress': 'Progress',
  'settings': 'Settings',
  'completed_items': 'Completed Exercises',
  'language': 'Language',
  'sound': 'Sound',
  'reset_progress': 'Reset Progress',
  'about': 'About App',
  'about_desc': '1300+ Exercises Hindi Handwriting Workbook with Voice.',
  'clear_canvas': 'Clear',
  'undo': 'Undo',
  'guide_lines': 'Ruled Lines',
  'watermark': 'Trace Watermark',
  'next': 'Next Practice',
  'previous': 'Previous',
  'voice': 'Voice',
  'categories': 'Categories',
  'search_hint': 'Search word, letter or meaning...',
  'congratulations': 'Awesome! Practice Complete!',
  'pen_color': 'Pen Color',
  'shuffle': 'Random Practice',
};
