const Map<String, String> enStrings = {
  'app_title': 'Hindi Counting Objects',
  'subtitle': 'Count Illustrated Objects & Learn Hindi Numbers',
  'start_learning': 'Start Counting',
  'practice': 'Counting Arena',
  'progress': 'Mastery & Progress',
  'settings': 'Settings',
  'prompt_prefix': 'How many',
  'prompt_suffix': 'can you see?',
  'tap_to_count': 'Tap objects to count them 1 by 1!',
  'select_correct': 'Select the matching number below:',
  'great_job': 'Excellent! 🎉 Correct Answer!',
  'try_again': 'Count again carefully 😊',
  'next': 'Next Challenge',
  'previous': 'Previous',
  'random': 'Random',
  'completed_items': 'Mastered Countings',
  'streak': 'Streak',
  'score': 'Points',
  'categories': 'Explore Categories',
  'mastery': 'Counting Mastery',
  'overall_progress': 'Overall Learning Progress',
  'reset_progress': 'Reset Progress',
  'reset_confirm': 'Are you sure you want to reset all counting progress?',
  'cancel': 'Cancel',
  'reset': 'Reset',
  'language': 'Language',
  'sound': 'Audio Voice',
  'about': 'About App',
  'about_desc': '1,200+ interactive visual object counting challenges with authentic Hindi voice and lively animations.',
};
