const Map<String, String> hiStrings = {
  'app_title': 'वस्तु गिनना सीखें',
  'subtitle': 'चित्रित वस्तुएँ गिनें और हिन्दी अंक सीखें',
  'start_learning': 'वस्तुएँ गिनें',
  'practice': 'गिनती अखाड़ा',
  'progress': 'निपुणता और प्रगति',
  'settings': 'सेटिंग्स',
  'prompt_prefix': 'यहाँ कितने',
  'prompt_suffix': 'हैं?',
  'tap_to_count': 'वस्तुओं को एक-एक करके गिनने के लिए छूएँ!',
  'select_correct': 'नीचे सही संख्या चुनें:',
  'great_job': 'शाबाश! 🎉 बिल्कुल सही उत्तर!',
  'try_again': 'ध्यान से फिर गिनें 😊',
  'next': 'अगली चुनौती',
  'previous': 'पिछला',
  'random': 'यादृच्छिक',
  'completed_items': 'सफल गणनाएँ',
  'streak': 'लगातार दिन',
  'score': 'अंक',
  'categories': 'सभी श्रेणियाँ',
  'mastery': 'गिनती निपुणता',
  'overall_progress': 'कुल सीखने की प्रगति',
  'reset_progress': 'प्रगति रीसेट करें',
  'reset_confirm': 'क्या आप सभी गिनती प्रगति को रीसेट करना चाहते हैं?',
  'cancel': 'रद्द करें',
  'reset': 'रीसेट',
  'language': 'भाषा',
  'sound': 'आवाज़ ध्वनि',
  'about': 'ऐप के बारे में',
  'about_desc': '1,200+ इंटरएक्टिव विज़ुअल ऑब्जेक्ट काउंटिंग चुनौतियाँ हिन्दी ध्वनि और सजीव एनिमेशन के साथ।',
};
