
const Map<String, String> enStrings = {
  'app_title': 'Hindi Easy Words',
  'subtitle': 'Learn 2 & 3 Letter Simple Hindi Words',
  'start_learning': 'Learn Words',
  'practice': 'Word Builder Game',
  'progress': 'My Progress',
  'settings': 'Settings',
  'two_letter': '2-Letter Words',
  'three_letter': '3-Letter Words',
  'all': 'All',
  'word_builder': 'Combine letters to build the word',
  'breakdown': 'Breakdown:',
  'completed_items': 'Completed Words',
  'total_score': 'Total Score',
  'great_job': 'Great Job! 🎉',
  'try_again': 'Try Again 😊',
  'next': 'Next',
  'replay': 'Replay',
  'language': 'Language',
  'sound': 'Sound',
  'sound_on': 'Sound On',
  'sound_off': 'Sound Off',
  'reset_progress': 'Reset Progress',
  'reset_confirm': 'Are you sure you want to reset your progress?',
  'cancel': 'Cancel',
  'confirm': 'Yes',
  'about': 'About App',
  'about_desc': '100% Offline 2 & 3 Letter Simple Hindi Words learning for kids.',
};
