
const Map<String, String> hiStrings = {
  'app_title': 'हिंदी सरल शब्द',
  'subtitle': '2 और 3 अक्षर वाले आसान शब्द सीखें',
  'start_learning': 'शब्द सीखें',
  'practice': 'शब्द बनाओ खेल',
  'progress': 'मेरी प्रगति',
  'settings': 'सेटिंग्स',
  'two_letter': '2 अक्षर वाले',
  'three_letter': '3 अक्षर वाले',
  'all': 'सभी',
  'word_builder': 'अक्षर जोड़कर शब्द बनाओ',
  'breakdown': 'अक्षर जोड़:',
  'completed_items': 'सीखे गए शब्द',
  'total_score': 'कुल अंक',
  'great_job': 'बहुत बढ़िया! 🎉',
  'try_again': 'फिर कोशिश करें 😊',
  'next': 'अगला',
  'replay': 'सुनें',
  'language': 'भाषा',
  'sound': 'ध्वनि',
  'sound_on': 'ध्वनि चालू',
  'sound_off': 'ध्वनि बंद',
  'reset_progress': 'प्रगति रीसेट करें',
  'reset_confirm': 'क्या आप वाकई प्रगति रीसेट करना चाहते हैं?',
  'cancel': 'रद्द करें',
  'confirm': 'हाँ',
  'about': 'ऐप के बारे में',
  'about_desc': 'बच्चों के लिए 100% ऑफ़लाइन 2 और 3 अक्षर वाले सरल शब्द।',
};
