const Map<String, String> enStrings = {
  'app_title': 'Hindi Picture Words',
  'subtitle': 'Identify 1,000+ illustrated picture words across 35+ categories',
  'start_learning': 'Picture Words',
  'practice': 'Picture Quiz Game',
  'progress': 'Progress Details',
  'settings': 'Settings & Audio',
  'tap_to_reveal': 'Tap picture to reveal name 👆',
  'completed_items': 'Mastered Picture Words',
  'language': 'Language',
  'sound': 'Voice & Sound',
  'reset_progress': 'Reset Progress',
  'reset_confirm': 'Are you sure you want to reset your picture words progress?',
  'cancel': 'Cancel',
  'confirm': 'Yes, Reset',
  'about': 'About App',
  'about_desc': '1,000+ Illustrated picture words with bilingual Hindi & English speech synthesis.',
  'all': 'All Picture Words',
  'animals': 'Animals & Birds',
  'fruits': 'Sweet Fruits',
  'vegetables': 'Vegetables',
  'body': 'Body Parts',
  'nature': 'Nature & Elements',
  'house': 'Home & Objects',
  'food': 'Food & Sweets',
  'clothes': 'Clothes & Wear',
  'vehicles': 'Vehicles & Transport',
  'professions': 'Jobs & Professions',
  'numbers': 'Numbers',
  'colors': 'Vibrant Colors',
  'actions': 'Actions & Verbs',
  'emotions': 'Feelings & Emotions',
  'school': 'School & Studies',
  'flowers': 'Flowers',
  'festivals': 'Festivals & Culture',
  'opposites': 'Opposite Words',
  'adjectives': 'Adjectives',
  'spices': 'Spices & Flavors',
  'instruments': 'Musical Instruments',
  'materials': 'Materials & Metals',
  'kitchen': 'Kitchen Utensils',
  'sports': 'Sports & Fitness',
  'time': 'Time & Calendar',
  'tech': 'Tech & Science',
  'geography': 'Geography & Landforms',
  'daily': 'Daily Phrases',
  'shopping': 'Shopping & Market',
  'health': 'Health & Medicine',
  'arts': 'Arts & Culture',
  'office': 'Office & Work',
  'environment': 'Environment & Climate',
  'tools': 'Tools & Hardware',
  'astronomy': 'Seasons & Astronomy',
  'places': 'Buildings & Places',
  'aquatic': 'Sea Life & Reptiles',
  'toys': 'Toys & Celebrations',
  'herbs': 'Herbs & Plants',
  'signs': 'Transport & Signs',
  'grooming': 'Cosmetics & Grooming',
  'search_hint': 'Search picture words...',
  'words_count': 'Total Words',
  'deck_mode': 'Picture Card Mode',
  'grid_mode': 'Picture Grid Mode',
  'previous': 'Previous',
  'next': 'Next',
  'shuffle': 'Shuffle',
  'listen_hi': 'Listen Hindi',
  'listen_en': 'Listen English',
  'voice_test': 'Voice Test',
  'voice_test_desc': 'Test speech synthesis pronunciation',
};
