const Map<String, String> enStrings = {
  'app_title': 'Hindi Daily Words',
  'subtitle': 'Learn and speak daily Hindi words',
  'start_learning': 'Start Learning',
  'practice': 'Practice',
  'progress': 'Progress',
  'settings': 'Settings',
  'language': 'Language',
  'sound': 'Sound',
  'sound_on': 'Sound On',
  'sound_off': 'Sound Off',
  'all': 'All',
  'home': 'Home',
  'school': 'School',
  'food': 'Food',
  'family': 'Family',
  'body': 'Body',
  'clothes': 'Clothes',
  'actions': 'Actions',
  'places': 'Places',
  'nature': 'Nature',
  'search_hint': 'Search words...',
  'favorites': 'Favorites',
  'no_favorites': 'No favorite words added yet',
  'completed_items': 'Completed Words',
  'total_score': 'Total Score',
  'great_job': 'Great Job! 🎉',
  'try_again': 'Try Again 😊',
  'correct_answer': 'Correct Answer!',
  'next': 'Next',
  'previous': 'Previous',
  'replay': 'Replay',
  'listen_and_choose': 'Listen and choose the correct picture',
  'mark_completed': 'Mark Completed',
  'about': 'About App',
  'about_desc': '100% Offline Hindi Voice Learning app designed for children.',
  'reset_progress': 'Reset Progress',
  'reset_confirm': 'Are you sure you want to reset your progress?',
  'cancel': 'Cancel',
  'confirm': 'Yes',
};
