const Map<String, String> hiStrings = {
  'app_title': 'हिंदी दैनिक शब्द',
  'subtitle': 'रोज़मर्रा के शब्द सीखें और बोलें',
  'start_learning': 'सीखना शुरू करें',
  'practice': 'अभ्यास करें',
  'progress': 'प्रगति',
  'settings': 'सेटिंग्स',
  'language': 'भाषा',
  'sound': 'ध्वनि',
  'sound_on': 'ध्वनि चालू',
  'sound_off': 'ध्वनि बंद',
  'all': 'सभी',
  'home': 'घर',
  'school': 'स्कूल',
  'food': 'खाना',
  'family': 'परिवार',
  'body': 'शरीर',
  'clothes': 'कपड़े',
  'actions': 'क्रियाएँ',
  'places': 'स्थान',
  'nature': 'प्रकृति',
  'search_hint': 'शब्द खोजें...',
  'favorites': 'पसंदीदा',
  'no_favorites': 'कोई पसंदीदा शब्द नहीं मिला',
  'completed_items': 'सीखे गए शब्द',
  'total_score': 'कुल स्कोर',
  'great_job': 'बहुत बढ़िया! 🎉',
  'try_again': 'फिर कोशिश करें 😊',
  'correct_answer': 'सही उत्तर!',
  'next': 'अगला',
  'previous': 'पिछला',
  'replay': 'फिर सुनें',
  'listen_and_choose': 'सुनें और सही चित्र चुनें',
  'mark_completed': 'पूर्ण चिह्नित करें',
  'about': 'ऐप के बारे में',
  'about_desc': 'बच्चों के लिए 100% ऑफ़लाइन हिंदी आवाज़ सीखने का ऐप।',
  'reset_progress': 'प्रगति रीसेट करें',
  'reset_confirm': 'क्या आप वाकई प्रगति रीसेट करना चाहते हैं?',
  'cancel': 'रद्द करें',
  'confirm': 'हाँ',
};
