const Map<String, String> enStrings = {
  'app_title': 'Hindi Number Pronunciation',
  'subtitle': 'Authentic Hindi Voice & Clear Articulation Studio',
  'start_learning': 'Pronounce Numbers',
  'categories': 'Explore Categories',
  'practice': 'Practice Studio',
  'progress': 'Mastery & Progress',
  'settings': 'Settings',
  'replay': 'Listen Again',
  'slow_speed': 'Slow Pronunciation (0.6x)',
  'normal_speed': 'Normal Speed (1.0x)',
  'listen': 'Tap to Pronounce',
  'pronounced': 'Pronounced',
  'completed_items': 'Mastered Words & Numbers',
  'streak': 'Streak',
  'score': 'Points',
  'mastery': 'Mastery',
  'overall_progress': 'Overall Learning Progress',
  'reset_progress': 'Reset Progress',
  'reset_confirm': 'Are you sure you want to reset all pronunciation progress?',
  'cancel': 'Cancel',
  'reset': 'Reset',
  'previous': 'Previous',
  'next': 'Next',
  'random': 'Random',
  'congrats': 'Brilliant!',
  'milestone_reached': 'Pronunciation milestone achieved!',
  'total_items': 'Total Words & Numbers',
  'about': 'About App',
  'about_desc': '1,200+ Hindi number and vocabulary pronunciations with authentic voice audio and interactive soundwaves.',
  'language': 'Language',
  'sound': 'Audio Voice',
};
