const Map<String, String> hiStrings = {
  'app_title': 'हिन्दी संख्या उच्चारण',
  'subtitle': 'स्पष्ट और मधुर हिन्दी उच्चारण स्टूडियो',
  'start_learning': 'संख्या उच्चारण सीखें',
  'categories': 'सभी श्रेणियाँ',
  'practice': 'उच्चारण अभ्यास',
  'progress': 'निपुणता और प्रगति',
  'settings': 'सेटिंग्स',
  'replay': 'दोबारा सुनें',
  'slow_speed': 'धीमी आवाज़ (0.6x)',
  'normal_speed': 'सामान्य गति (1.0x)',
  'listen': 'उच्चारण सुनने के लिए दबाएँ',
  'pronounced': 'उच्चारित',
  'completed_items': 'सीखे गए शब्द व संख्याएँ',
  'streak': 'लगातार दिन',
  'score': 'अंक',
  'mastery': 'निपुणता',
  'overall_progress': 'कुल सीखने की प्रगति',
  'reset_progress': 'प्रगति रीसेट करें',
  'reset_confirm': 'क्या आप सभी उच्चारण प्रगति को रीसेट करना चाहते हैं?',
  'cancel': 'रद्द करें',
  'reset': 'रीसेट',
  'previous': 'पिछला',
  'next': 'अगला',
  'random': 'यादृच्छिक',
  'congrats': 'शानदार!',
  'milestone_reached': 'उच्चारण उपलब्धि प्राप्त की!',
  'total_items': 'कुल शब्द व संख्याएँ',
  'about': 'ऐप के बारे में',
  'about_desc': '1,200+ हिन्दी संख्या और शब्दावली उच्चारण ध्वनि और लाइव साउंडवेव के साथ।',
  'language': 'भाषा',
  'sound': 'आवाज़ ध्वनि',
};
